### ISSUE TITLE
Broken color identifier link

### ISSUE THREAD

**Issue by fabiospampinato** [Microsoft/vscode-docs#1132]
Under [DecorationRenderOptions](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-namedecorationrenderoptionsaspan-classcodeitem-id280decorationrenderoptionsspan) backgroundColor's section it says "Alternativly a color from the color registry an be [referenced](https://code.visualstudio.com/docs/extensionAPI/vscode-api#ColorIdentifier)."

Apart from the typo in "**c**an", the issue is that the page "referenced" is supposed to point to doesn't exist, additionally searching `Identifier` (part of the url) doesn't lead to anything.

**Comment by gregvanl** [comment]
@fabiospampinato Thank your for reporting the issue. The vscode-api topic is auto-generated from our vscode.d.ts. This was fixed with https://github.com/Microsoft/vscode/commit/883a3fee3642c73cfd75990938c2d18eaa53741b. The vscode-api topic won't be updated until our next September release (out early October) when we re-generate the API doc.
