### ISSUE TITLE
Can you change extensionTestsPath?

### ISSUE THREAD

**Issue by gauntface** [Microsoft/vscode-docs#1271]
Under these docs:

https://github.com/Microsoft/vscode-docs/blob/master/docs/extensions/testing-extensions.md#launch-tests-configuration

It calls out that .vscode/launch.json has the definition `"--extensionTestsPath=${workspaceRoot}/test"` which it does but changing the directory doesn't actually seem to affect anything. I.e. the command line just reads the same test directory and it's pretty difficult to reason with.

Is it possible to change the directory or is there some sort of caching of the value?

**Comment by gregvanl** [comment]
@gauntface I just tried renaming the 'extensionTestsPath' setting in launch.json and also the folder name and VS Code seemed to track the setting change. This also sounds more like a VS Code product issue rather than a documentation issue, so if you are still having an issue, I recommend opening an issue in the VS Code product repo https://github.com/Microsoft/vscode/issues
