### ISSUE TITLE
Does Visual Studio Code include npm?

### ISSUE THREAD

**Issue by andersea** [Microsoft/vscode-docs#14]
The office add-in page claims VSCode includes npm.

https://code.visualstudio.com/Docs/runtimes/office

However I can't seem to find it in my install. I don't have node.js installed.

From the link: 

## Prerequisites
To run the Yeoman Office Add-in generator, you need a few things:

- [NPM](https://www.npmjs.com/) (*Visual Studio Code includes this*)

**Comment by scottaddie** [comment]
I don't believe NPM is included, and you would need Node.js installed in order to use it. The easiest way to track down whether you have NPM is to open a command shell and type `where npm`.

On Windows, you should see NPM in these locations:
1) C:\Program Files\nodejs
2) %APPDATA%\Roaming

My recommendation is to install Node.js from nodejs.org, and that will take care of everything for you, including the installation of NPM.

**Comment by scottaddie** [comment]
After trying this on 2 different machines, I can now say with 100% certainty that NPM does NOT get installed with VS Code. My latest pull request addresses this error in the docs.

**Comment by andersea** [comment]
Thanks for investigating!

**Comment by gregvanl** [comment]
Scott updated the documentation and removed the claim that npm is included.  Thanks Scott.
