### ISSUE TITLE
Rename "Debugging API"

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-docs#1446]
I suggest to rename "Debugging API" to "Debugger Extension API" or "Debug Extension API" to better align with "Source Control API" and "Markdown Extension API".

**Comment by gregvanl** [comment]
After consideration, I still like "Debugging API" over the other options. Adding "Extension" in the title isn't necessary since the topic in under the Extensibility Reference TOC node and would cause the topic name to wrap onto two lines. "Extension" was necessary with "Markdown Extension" since it is an API for Markdown plugins.
