### ISSUE TITLE
Running VS Code from Run Command Prompt is causing CMD Window to pop up

### ISSUE THREAD

**Issue by YuriySamorodov** [Microsoft/vscode-docs#1504]
**Issue**
If you put VS Code bin in %PATH% variable, the following  can be noticed:

1. User opens Run command Prompt either with either Windows key + R combination or directly through menu
2. User types "code" in Run command prompt
3. Cmd.exe starts
4. Visual Studio Code appears

**Root Cause**
The root cause of the issue is that VSCode installer adds the following string in %PATH% variable:  
C:\Program Files\Microsoft VS Code\bin  
That makes code.cmd executable start when user calls "code" from Run command prompt.

**Workaround**
If you want to run Code.exe instead of code.cmd, you may want to change value in %PATH% from "C:\Program Files\Microsoft VS Code\bin" to "C:\Program Files\Microsoft VS Code"

**Request**
Would it be possible to adjust installer settings so that it puts "C:\Program Files\Microsoft VS Code" in %PATH% variable?  
Otherwise I probably can make a pull request with the note on how to start VS Code directly.

**Comment by joaomoreno** [comment]
The current PATH variable value is purposeful.

This is a consequence of Electron's architecture and the lack of having our own exe launcher. Electron.exe doesn't let us have a stdout, when running normally, only when running with `ELECTRON_RUN_AS_NODE`. In order to implement all the CLI tasks (`--install-extension`, etc) we simply can't let Code.exe be in the PATH. Instead, we use `code.cmd` for that: it sets up the right environment which lets us run Electron as a command line tool.

Typing `code` in `Run` and having a command prompt open up is a sad consequence of all this mess... We can't fix it until we create our own exe. There's already an issue on Microsoft/vscode for this.

**Comment by moymike** [comment]
I just had this issue.  When hitting the Win key, then typing 'code' and hitting enter.  Code opened  and so did a cmd window.  

The fix was simple and doesn't appear to cause any issue.  Hit the Win key and type code, instead of hitting enter, click open file location on the right side of the box.  The file it was going to launch was 'code.cmd' ....  I renamed it to 'code.cmd.old' and now when I hit Win key / code to launch, it finds the 'Visual Studio Code' shortcut instead of the 'code.cmd'.

This was only happening on my laptop, no idea what changed that caused windows to get pointed at the 'code.cmd'

**Comment by kevincharp** [comment]
Si pongo en mis variables de entorno la siguiente ruta "C:\Program Files\Microsoft VS Code\" y cambio el nombre del archivo .exe de "code.exe" a "vscode.exe" tendria consecuencias para el funcionamiento correcto de VS Code?

A simple viste parece una posible solución que evita que se abra una ventada de cmd cuando ejecuto run vscode que ateriormente era run code

**Comment by assarbad** [comment]
Actually you could have a `code.com` (still actually being a Portable Executable) which could be a console application (thereby implicitly acquiring stdin, stdout and stderr) and it'd take precedence unless someone tampers with the `PATHEXT` variable. By default the `PATHEXT` variable will be used to complete the extension of some token. So if you "execute" `code` it'll first look for `code.com`, then `code.exe`, then `code.bat` ... you get the idea.

Visual Studio itself uses this scheme by providing a `devenv.com` and `devenv.exe` the former being a console application with the mentioned traits and the latter being a GUI ("windowed") application.

```
$ dumpbin /nologo /headers devenv.com|findstr subsystem
            6.00 subsystem version
               3 subsystem (Windows CUI)
$ dumpbin /nologo /headers devenv.exe|findstr subsystem
            6.00 subsystem version
               2 subsystem (Windows GUI)
```

This very same scheme could as well be used here.

The `devenv.com` essentially just does roughly the following:

* gets command line (`GetCommandLineW`)
* looks for `.com` and replaces it by `.exe`
* gets current startup info (`GetStartupInfoW`)
* gets handle for stdout (`hStdOut`) using `GetStdHandle(STD_OUTPUT_HANDLE)`, but not for stdin (uses `NULL`), initializes pipes to be used for stdin and stdout, attaches them to the respective members of the `STARTUPINFOW` struct (see [this](https://learn.microsoft.com/windows/win32/ProcThread/creating-a-child-process-with-redirected-input-and-output)) -- i.e. write end of stdout pipe for `hStdOutput` and read end for stdin pipe for `hStdInput`
* sets a Control+C handler
* sets an environment variable (locally) `vsconsoleoutput=1` (`SetEnvironmentVariableW(L"vsconsoleoutput", L"1")`)
* creates the process from the `.exe` using `CreateProcessW`
* closes handles for the `stdin` and `stdout` pipe ends passed via `STARTUPINFOW` struct
* in a loop
    * reads from read end of stdout pipe using `ReadFile` until no more bytes can be read
    * writes to `hStdOut`
* removes the previously set environment variable (locally) again (`SetEnvironmentVariableW(L"vsconsoleoutput", NULL)`)
* closes all handles other than `PROCESS_INFORMATION::hThread` and `PROCESS_INFORMATION::hProcess` and `hStdOut`
* waits for `PROCESS_INFORMATION::hProcess` infinitely
* retrieves its exit code
* closes remaining handles
* exits with exit code retrieved from the `devenv.exe`
