### ISSUE TITLE
Add Ember tutorial

### ISSUE THREAD

**Issue by yohanmishkin** [Microsoft/vscode-docs#1509]
Similar to React and Angular tutorials. 

Include:
- IntelliSense and code navigation
- Client side debugging

**Comment by gregvanl** [comment]
Only 3 upvotes so closing for now.

**Comment by acorncom** [comment]
@gregvanl I can get you some more upvotes, those items above would be greatly appreciated. How many votes do you want to see? :grinning:

**Comment by gregvanl** [comment]
Well, alrighty then, reopening. 🙂

**Comment by sivakumar-kailasam** [comment]
As a long time vscode user(fan) I'm disappointed by the fact that this issue was closed on the grounds of popularity. 

If the response from a maintener of this repo was to ask for a PR implementing this that might have been more relevant. 

If other frameworks are already mentioned in the documentation I don't see why it has to be a popularity contest for new additions to make it there. While it's easy to brush off the above as a frustrated rant from an ember maintainer, I'm voicing out my opinion so that the next person doesn't have to face this (you might not have intended to do this but please ensure that it wouldn't happen again)

**Comment by gregvanl** [comment]
Ember enthusiasts: Feel free to provide suggestions or PRs for https://github.com/Microsoft/vscode-docs/blob/master/docs/nodejs/emberjs-tutorial.md.
Unfortunately, the client-side debugging story isn't great and I've provided some context in a Common questions entry.
