### ISSUE TITLE
Update Python linting docs w/ info on linting on change

### ISSUE THREAD

**Issue by marnovo** [Microsoft/vscode-docs#1613]
Update Python linting docs w/ info on linting on change:

Target file/documentation: [docs/python/linting.md](https://github.com/Microsoft/vscode-docs/blob/master/docs/python/linting.md)

Based on: https://github.com/Microsoft/vscode-python/pull/1231
which implements: https://github.com/Microsoft/vscode-python/issues/408

**Comment by kraigb** [comment]
@DonJayamanne @brettcannon @MikhailArkhipov Can one of you confirm that the Python extension supports python.linting.lintOnTextChange now? I didn't see a doc issue for it before, the setting does appear now in the current release.

**Comment by brettcannon** [comment]
This is only for the experimental analysis engine, so this is not something to document yet.

**Comment by kraigb** [comment]
@marnovo With Brett's response, I'm closing this issue because the lint-on-change capability isn't officially supported yet. When it is, we'll be creating a suitable issue here aligned with the release of the extension that contains it, so in the meantime we won't maintain this present issue on a backlog.

**Comment by marnovo** [comment]
Thanks for the clarification, @kraigb & @brettcannon.

Looking forward to the official release of the analysis engine, particularly this feature.
