### ISSUE TITLE
Make user/workspace settings documentation more obvious

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#163]
Users are confused when the documentation calls out a setting without indicating how to set it through File | Preferences.  We should review the docs and provide `settings` links to the userandworkspace.md topic.

**Comment by gregvanl** [comment]
We should probably move the User and Workspace settings topic back to Editor. Right now it is hidden in Customization.

**Comment by gregvanl** [comment]
Also make sure commonly requested settings are discoverable
- wordwrap
- autosave
- ruler setting (new feature in February)

**Comment by JanKok** [comment]
I've submitted a pull request to add a short "Changing Settings" section near the top of codebasics.md. Maybe you could accept that change and add a link to the more extensive Customizations section.

**Comment by gregvanl** [comment]
Hi Jan,
I like your pull requests and you are right that they fall under this work item.  I've been analyzing our doc feedback verbatim and settings is an area of confusion for new users.  
I should be able to review and merge your pull requests shortly. 
We really appreciate your input and fresh eyes on our docs.
Thanks
- Greg

**Comment by TravisTheTechie** [comment]
It would be really great if you link to a specific section of the default config. Since it's a code block, I'm guessing this will be really unlikely unless someone makes an hash-to-search-to-scrollto magic script. I'd also be concerned about degraded experience if someone is blocking JS or JS fails for some reason.

**Comment by TravisTheTechie** [comment]
Brittle, so maybe not worth using, but...

```javascript
var possibleCodeElements = document.querySelectorAll("code.json span.hljs-attribute");
for(var i = 0; i < possibleCodeElements.length; i++) { 
    var element = possibleCodeElements[i]; 
    if (element.innerText === "files.exclude") { 
        element.scrollIntoView(true);
    } 
}
```

Does scroll to the "files.exclude" section. So you could add a query or hash to the URL and use that to find the content then scroll to it.

**Comment by gregvanl** [comment]
Thanks for the suggestion, Travis.  While we have the Default Settings in userandworkspace.md, it is there mostly for search and we prefer the user to search and review Default Settings in VS Code directly through File | Preferences | User/Workspace Settings.

**Comment by gregvanl** [comment]
Addressed codebasics.md settings issues with https://github.com/Microsoft/vscode-docs/commit/a404600224bfba8b4c927c17f41e23087a023714.
Also added a Commen Question on configuring word wrap.

**Comment by gregvanl** [comment]
verbatim: "When do changed settings get loaded?  Is it when settings.json is saved?"
Need to answer this question as part of this work.

**Comment by egamma** [comment]
>"When do changed settings get loaded? Is it when settings.json is saved?"

correct, the settings file is watched and code applies the settings when the file is saved.
With auto save on, this makes it feel like the settings are applied instantly.

**Comment by JanKok** [comment]
@gregvanl Thanks for accepting my changes. However, I think the Changing Settings section should go earlier in the codebasics doc, somewhere before the first reference to changing settings, which is in the Explorer section. My original thought was to place it near the beginning (as I did) because that would make it more memorable.

I think the title of that section should be Changing Settings, or at least _something_ about Settings, and not Configuring the Editor, because when I saw the line "Use the files.exclude setting to configure rules..." I immediately started searching for a settings button or menu entry or help about "settings".

Note also that there is a CUSTOMIZATION article heading. Customization, configuration, changing... too many synonyms for the same thing!

**Comment by JanKok** [comment]
Note these lines in codebasics in the Explorer section:

> ...and select Open in Terminal (or Open in Command Prompt on Windows).

> ...and selecting Reveal in Explorer (or Reveal in Finder on the Mac or Open Containing Folder on Linux).

This is a bit jarring to read because the first line describes the menu entry for Linux and Mac first and Windows last, while the second line lists Windows first, Mac second and Linux last.

I don't care which order the OSs are listed in, but please use a consistent order. (Maybe in order of expected size of user base?)

**Comment by gregvanl** [comment]
Good suggestion about reordering commands in the Explorer section.  https://github.com/Microsoft/vscode-docs/commit/e5925af2ea7126bc69ed3992d3e43804a0c224cf

**Comment by gregvanl** [comment]
Addressed by adding Settings topic to /docs First Steps section
