### ISSUE TITLE
Using Django in Visual Studio Code

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode-docs#1744]
_From @arangates on July 24, 2018 14:45_

saw the new tutorial released for Flask and its awesome ... can we get the same for Django ? 
https://code.visualstudio.com/docs/python/tutorial-flask

_Copied from original issue: Microsoft/vscode#54947_

**Comment by gregvanl** [comment]
_From @vscodebot[bot] on July 24, 2018 14:45_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [Can't debug Django applications any longer (#52121)](https://www.github.com/Microsoft/vscode/issues/52121)

**Comment by gregvanl** [comment]
_From @kieferrm on July 24, 2018 23:26_

@gregvanl one for vscode-docs.

**Comment by kraigb** [comment]
@arangates, I'm delighted that you enjoyed the Flask tutorial! And yes, I have a similar treatment for Django tutorial on my task list for early September (after I return from a longer vacation that occupies most of August; otherwise I'd be doing it sooner).

In the meantime, you might be interested in the Django tutorial I wrote for Visual Studio (on Windows), https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-01-project-and-solution. I know the tooling details won't be particularly relevant to VS Code, but the discussion of how Django works might be helpful. Much of what the Visual Studio project templates generate is what's produced by CLI commands like django-admin startproject, as mentioned in the tutorial, so you might be able to use that as a starting point.

Feel free to include any requests here that you'd like to see in the tutorial.
