### ISSUE TITLE
Could not install packages due to an EnvironmentError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by AMDphreak** [Microsoft/vscode-docs#1850]
Mac OS X:

```
$ sudo python -m pip install matplotlib
...
Installing collected packages: backports-abc, futures, singledispatch, tornado, nose
Could not install packages due to an EnvironmentError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/man'
```

Full log
[https://pastebin.com/3L5qY5Yi](https://pastebin.com/3L5qY5Yi)

Following the tutorial:
https://code.visualstudio.com/docs/python/python-tutorial#_prerequisites

I noticed that it says this:

```
Requirement already satisfied: matplotlib in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (1.3.1)
```

However, my debugger complains that this package is not installed (I'm using python 3.7 from another directory and am not sure if packages are shared between the versions). Still, installing the package to 2.x should not exit with errors.

**Comment by kraigb** [comment]
@AMDphreak Does your solution using `sudo python3 -m pip install matplotlib` from the other issue work? Seems like it should, so that you're not trying to install into the Python 2.7 environment.

**Comment by kraigb** [comment]
I'm assuming that you found a suitable solution, so I'm closing this issue.

**Comment by AMDphreak** [comment]
> I'm assuming that you found a suitable solution, so I'm closing this issue.

Yes I did.

**Comment by pottangibalu** [comment]
sudo pip install pyspark
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: The directory '/Users/xxxx/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyspark
  Downloading pyspark-2.4.5.tar.gz (217.8 MB)
     |████████████████████████████████| 217.8 MB 11.5 MB/s 
Collecting py4j==0.10.7
  Downloading py4j-0.10.7-py2.py3-none-any.whl (197 kB)
     |████████████████████████████████| 197 kB 12.0 MB/s 
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-2.4.5-py2.py3-none-any.whl size=218257927 sha256=cb9069939333109e83fb4a29c6567b796af39cffd9c36f8c79d3e14860371fe0
  Stored in directory: /private/tmp/pip-ephem-wheel-cache-t78OHw/wheels/2c/3f/5d/7d065af3ed50810487223f5c8a93f9ce0e7648d34b040da237
Successfully built pyspark
Installing collected packages: py4j, pyspark
ERROR: Could not install packages due to an EnvironmentError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/share'





It works (pip install pyspark) without sudo on Mac.



$ pip install pyspark
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Collecting pyspark
  Downloading pyspark-2.4.5.tar.gz (217.8 MB)
     |████████████████████████████████| 217.8 MB 9.2 kB/s 
Requirement already satisfied: py4j==0.10.7 in /Library/Python/2.7/site-packages (from pyspark) (0.10.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-2.4.5-py2.py3-none-any.whl size=218257927 sha256=4e3a0ab10f496f68fa485fc2cc0a8c699236756b5463dc520bbf708e55c42598
  Stored in directory: /Users/xxxx/Library/Caches/pip/wheels/2c/3f/5d/7d065af3ed50810487223f5c8a93f9ce0e7648d34b040da237
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-2.4.5
