### ISSUE TITLE
Ordering of what can extensions do?

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode-docs#2122]
I thought it would be good to start with Language Extensions followed Debug, Tasks, and UI extensions

- Language Extensions Overview
- Dynamic Language Features
- Debug
- Task
- Theme
- Views

Do not know if it makes sense, but I thought starting with language extensions would be good as VS Code is an editor and most of the top 100 extensions are language based

**Comment by octref** [comment]
Ranked them by popularity. Theming still goes first since they take a very different path than most other extension authors. And you can argue not only extension authors but ordinary users would want to know more about theming too.

![image](https://user-images.githubusercontent.com/4033249/47736454-f2340500-dc2b-11e8-9180-203847ea1823.png)
