### ISSUE TITLE
Python tutorial hello file creation

### ISSUE THREAD

**Issue by mrcbsbr23** [Microsoft/vscode-docs#2156]
After the following instruction in the VS Code Python tutorial;

Create a Python Hello World source code file
From the File Explorer toolbar, click the New File button on the hello folder:

When I was following the tutorial the hello folder was not created after I opened VS Code after creating the hello folder.  I had to click on "Open Folder" and select the hello folder created and then click on the new file button to create the hello.py file.

**Comment by gregvanl** [comment]
Hi @mrcbsbr23 Did you navigate to the new folder before launching VS Code?

```
mkdir hello
cd hello
code .

```

**Comment by mrcbsbr23** [comment]
Good Day!

I tried originally navigating and creating the file using File Explorer.  When I entered into the hello folder I used File>Open Windows PowerShell.  The hello folder did not open automatically.

I tried navigating through PowerShell terminal and did the same.  Now I just found out from your email about typing a period after code, I did not notice it in the webpage.  That is the reason why the folder did not appear in VS Code, I verify it.  When I used a long time ago the Command prompt I never use a period.  I guess I thought that PowerShell was the same.

Can you tell what other uses are for typing a period or point me towards a reference that I could use?

Thank you for your help.

Marcobis

PS
Just in case…I want to take the opportunity to ask about Source Control.  I install Git and set the git.path variable to the path C:\\Program Files\\Git\\git.exe replacing “null”.  When I go to source control, at the right of Source Control there is a symbol that appears to resemble Git.  Does this means that it is appropriately setup in VS Code even though it says below “No source control providers registered.”?

Sent from Mail for Windows 10

**Comment by gregvanl** [comment]
https://code.visualstudio.com/docs/editor/command-line#_launching-from-command-line
As to Git, sounds like you are configured correctly. Try opening a folder which is under Git source control.

**Comment by mrcbsbr23** [comment]
Thank you.  I do not know how to open a folder under Git source control.  I saw a picture of Source Control and I saw that I just have the Git icon but not the three periods that are after the symbol.  Please let me know how I can proceed.

Sent from Mail for Windows 10

**Comment by gregvanl** [comment]
HI @mrcbsbr23 You can learn about Git through the on-line book https://git-scm.com/doc as well as the GitHub site https://guides.github.com/activities/hello-world.
If you clone a Git repository to your local machine, you can then open VS Code in that new folder and the Source Control view will detect that the project is under Git source control.
If you don't want to create a GitHub account, you can make any project include a local Git repository by running git init https://git-scm.com/docs/git-init.
Closing this issue since there doesn't seem to be a VS Code documentation issue.
The VS Code Version Control topic also has helpful links for learning Git https://code.visualstudio.com/docs/editor/versioncontrol#_git-support
