### ISSUE TITLE
Run Python File in Terminal - syntax error

### ISSUE THREAD

**Issue by susanin76** [Microsoft/vscode-docs#2248]
Every time I right click and try to run edited python file a syntax error is raised from terminal.
no issues so far with Shift+Enter or  Run Selection/Line.
what's wrong? thanks

**Comment by susanin76** [comment]
I attach the terminal output:

>>> /Users/user/miniconda3/bin/python /Users/user/miniconda3/Programmazione/example1.py
  File "<stdin>", line 1
    /Users/user/miniconda3/bin/python /Users/user/miniconda3/Programmazione/example1.py
    ^
SyntaxError: invalid syntax

**Comment by kraigb** [comment]
What code are you trying to run?

**Comment by susanin76** [comment]
price_list=[100,86,76,70,84,90,75,78,72,60]
gain = 0
minSofar=price_list[0]
for day in range(len(price_list)):
    minSofar = min(minSofar, price_list[day])
    gain = max(gain, price_list[day] - minSofar)
print(gain)

but it doesn't work at all with any code...

**Comment by kraigb** [comment]
@susanin76 I tried you code in my own installation and it worked fine. I expect, then, that it's an issue with your selected environment, which looks like miniconda. Have you tried it with a different interpreter?

In the end, your issues sounds much more like an issue with the extension, rather than the docs (which is what this present repo is for). In that case, can you repost on https://github.com/microsoft/vscode-python/issues?

**Comment by kraigb** [comment]
Closing this issue as it's a product bug rather than docs, and should be filed on https://github.com/microsoft/vscode-python/issues.

**Comment by hyansuper** [comment]
Hi, 
have you solved the problem? I have the same issue.
