### ISSUE TITLE
Not much info about ProgressLocations

### ISSUE THREAD

**Issue by tetchel** [microsoft/vscode-docs#2422]
https://code.visualstudio.com/api/references/vscode-api#ProgressLocation

> A location in the editor at which progress information can be shown. It depends on the location how progress is visually represented.

That makes sense! But I'd like it to say in that doc section, possibly with a screenshot, exactly where each of the `ProgressLocations` is displayed in the editor. `Notification` is straightfoward, but the other two are more subtle and I had to do a bit of experimenting to figure out where that progress actually showed up.

In addition, there's some info in the TSDoc that would probably be useful in that API doc section too, namely that `Window` and `SourceControl` don't support cancellation or discrete progress. Those two locations also don't appear to display the progress `title`, but I could be wrong about that.

**Comment by gregvanl** [comment]
Hi @tetchel Thanks for taking the time to open an issue. The vscode-api topic is auto-generated from the vscode.d.ts file and current doesn't support pulling in the comments for enums. Sounds like you are unblocked after looking at vscode.d.ts and the IntelliSense it provides. Closing this now since we don't have plans in the near future to update the API reference generation.
