### ISSUE TITLE
Remove the HTML concatenation examples

### ISSUE THREAD

**Issue by GeekTrainer** [Microsoft/vscode-docs#2447]
The write-ups for getting started with [Flask](https://code.visualstudio.com/docs/python/tutorial-flask) and [Django](https://code.visualstudio.com/docs/python/tutorial-django) are **fantastic**! However, I'd love to see the example of HTML concatenation, which is called out as a bad practice, removed from the example. If it's something developers shouldn't be doing, it's probably best to leave it out of the docs.

**Comment by kraigb** [comment]
Thanks for the suggestion. I have those examples with the warning comments in the tutorials to make it completely clear, by way of a non-working counter-example, that you shouldn't use inline HTML, and that it's ultimately best to separate concerns with HTML in the template and data in the code. That is, you can see the results of both, and doing such experimentation typically results in better retention of the right practice than if we show only the best practice by itself.

Put another way, by showing only the best practice, a number of readers, not knowing any better and not just taking our word for it, are like going to wonder whether inline HTML might be a good idea. They might experiment on their own and have some kind of partial success, and end up spending a bunch of time trying to make it work better even though it doesn't work at all.

In short, I've included these counter examples to make the non-working inline HTML fully explicit, so that one is more willing to accept the best practice of separation of concerns, and leaves with a better understanding than they might otherwise. And given that the tutorials are very highly rather and that yours is the first suggestion to alter those parts, I'm inclined to leave it as-is.

Thoughts?

**Comment by GeekTrainer** [comment]
I want to reiterate I **love** the tutorial. I think you did a wonderful job building it. It's clear, easy to follow, and tells a great story. Writing content like this isn't easy (I know), and you put forth a wonderful write-up.

My concern comes from conversations I've had recently with both students and educators. One of the challenges they're running into is trying to figure out what the best practices are for security, and are looking for examples of what to do. This is why I'm concerned about a sample which has readers follow a bad practice.

I grok showing a bad practice can sometimes be helpful as it clearly shows what **not** to do. There is value there. But I'd rather see that as a clear "don't do" rather than having a reader do it, but telling them they shouldn't when it comes to building a site.

The opening paragraph clearly states building HTML dynamically is a terrible idea, which is wonderful. Maybe the sample itself could skip the step of using the bad code, and instead simply show an example snippet and link to docs so a reader could learn more about XSS on their own?

I'd propose the intro for the section look like the following:

### Use a template to render a page

The app you've created so far in this tutorial generates only plain text web pages from Python code. Although it's possible to generate HTML directly in code, developers typically avoid such a practice because it's vulnerable to [cross-site scripting (XSS) attacks](http://flask.pocoo.org/docs/1.0/security/#cross-site-scripting-xss). The following code would allow an attacker to inject their own HTML or scripts into your site:

```
@app.route("/hello/<name>")
def hello_there(name):
    match_object = re.match("[a-zA-Z]+", name)

    if match_object:
        clean_name = match_object.group(0)
    else:
        clean_name = "Friend"

    ## BAD PRACTICE - You should never concatenate HTML in your code
    content = "<h1>Hello there, " + clean_name + "!</h1>
    return content
```

Instead, developers separate HTML markup from the code-generated data that gets inserted into that markup. Templates are a common approach to achieve this separation, and offer better security.

--- And then from here the "good example" could start

**Comment by kraigb** [comment]
Yes, I like your suggestion. Let me work with that approach, maybe even to include less code and even put it inline rather than a code block.

**Comment by kraigb** [comment]
@GeekTrainer, can you review PR #2463 for me? I edited both Flask and Django tutorials, and suggested at the end of the section to try using a name with <>'s in it, to see the escaping. This allowed me to drop the questionable code block altogether. Let me know if you see anything to tweak.

**Comment by GeekTrainer** [comment]
All of it looks great! Thanks for being open to the suggestion. And the shorter block with the inline code flows better as well.
