### ISSUE TITLE
We should adhere to a common style guide for consistency

### ISSUE THREAD

**Issue by kyerlasswell** [Microsoft/vscode-docs#2469]
With so many people with different voices and writing styles from people contributing to something as language-heavy as documentation, it would be beneficial to require adherence to a common style guide that everyone can refer to for grammar and usage questions. Perhaps the [Microsoft Writing Style Guide](https://docs.microsoft.com/en-us/style-guide/welcome/)?

I see two major benefits: 

1. It ensures a consistent, coherent, and professional voice across all the pages.

2. It acts as a resource to refer to when grammar, usage, and general style questions arise (e.g. what's the difference between that and which?) or when to use/not use certain punctuation (like commas or semicolons).

Coming from a background in journalism and adhering to Associated Press Style, I know first-hand the benefits of a team of people being able to refer to a common resource to answer these types of questions instead of everyone giving it their best guess and ending up with an inconsistent product.

**Comment by gregvanl** [comment]
Hi @kyerlasswell Thank you for your interest in the VS Code documentation and your suggestion. The VS Code documentation has a "developer-to-developer", conversational style and this is intentional. We want readers to feel like they are hearing from the dev team, and in fact, the engineers have a big part in creating the docs. We welcome issues or PR for inaccuracies or changes which bring clarify to the content.
