### ISSUE TITLE
--help and --wait doesn't work with the zip insiders version.

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode-docs#252]
I tried using both vscode-insiders and vscode-git --help just opens the editor, same with --wait.

Arch Linux 64bit kernel 4.4.5.
- git version installed by hand.
- 0.10.13-insider version using a modified PKGFILE based on https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=visual-studio-code to get the insiders package instead.

**Comment by Tyriar** [comment]
The reason is that the bin command with `--help` is only shipped with the deb/rpm packages right now. This issue will get around this https://github.com/Microsoft/vscode/issues/4426

Is there any reason you didn't use the packages? You can always just extract them like the zip instead of installing.

**Comment by OneOfOne** [comment]
I didn't look into the deb/rpm, but for the zip I just put it in /opt and symlink code-insiders to ~/bin/code and it works.

**Comment by Tyriar** [comment]
I think I'll go ahead and reopen https://github.com/Microsoft/vscode/issues/4426 which will move the launcher to the zip alongside the electron binary, then the deb package can symlink to that. In the meantime I recommend installing via package since it's available on the insiders build now.
