### ISSUE TITLE
What is the difference between VS Code and VS Community? -- Weird answer

### ISSUE THREAD

**Issue by ReinisV** [Microsoft/vscode-docs#2557]
The answer seems to be answering a different question than the one being asked (i.e. what is the community version? VSCode is a code editor for debugging and version control)
https://github.com/Microsoft/vscode-docs/blob/master/docs/supporting/faq.md#what-is-the-difference-between-vs-code-and-vs-community

![image](https://user-images.githubusercontent.com/10805335/56030902-ac28b480-5d26-11e9-90e9-32265f5024e0.png)

**Comment by gregvanl** [comment]
Hi @ReinisV Does the update https://github.com/Microsoft/vscode-docs/commit/611de5d7ce0dd2aaffc4f3e5785c3f456affdd78 help make this clearer? There wasn't a good name for the original Visual Studio so we used "VS Community" which was the free version. I can see how this could be confusing since "community" also means a group of people and is a popular way to talk about open source contributors. Now we can say "Visual Studio IDE" to refer to the earlier Visual Studio and hopefully it is clear that we are talking about two different tools.

**Comment by ReinisV** [comment]
Yeah, awesome, thanks. Now it is a lot clearer.
