### ISSUE TITLE
Unity docs need a review / rework

### ISSUE THREAD

**Issue by mattbierner** [microsoft/vscode-docs#2722]
I was trying to configure VS Code as my C# editor for Unity and the existing docs were not helpful. This made the getting started experience pretty frustrating. 

Some notes on what I ran into and ideas on improving this:

* Update images to use latest unity version and latest VS Code version.

*  Recent versions of Unity may not generate a `sln` file?  This is required for IntelliSense for the Unity functions themselves. See https://forum.unity.com/threads/cant-get-vscode-to-work-properly-with-unity.538224/ for details. 
    
    We should Include the steps about setting up a project (sln file) up front instead of in the `Common questions` section. This was the number one issue I ran into as by default most unity tutorial have you opening individual scripts, not projects

* The `editing evolved` section is not useful as it just lists things that should work. In my case they were not working and I had no clue why so this section just annoyed me.

    This section should be reworked to have more prominent links to the VS Code and c# docs. Also the images should showcase IntelliSense for Unity functions. For a while I wasn't even sure if IntelliSense was supposed to work for the Unity functions because the docs were so vague.

* Under `Enabling code completion`, I have no idea what a `targeting pack` is and the Mac link just goes to https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/intro#macos Is this required?

* The Mono page we link to has a "Visual Studio" channel. I don't think this is what most users want as it has nothing to do with VS Code, but the name is super confusing. We should make it clearer that you should install Mono `Stable`

* Add links to help users investigate issues like IntelliSense not working. For example, checking the Omnisharp output channel may be helpful

**Comment by json2d** [comment]
Yeah it seems kinda dated. I just went through the setup on a Windows machine and it was a pain.

> * Under `Enabling code completion`, I have no idea what a `targeting pack` is

Apparently (for Windows atleast) now you have to install it through the "Developer pack", according to this https://github.com/OmniSharp/omnisharp-vscode/issues/2555#issuecomment-424128180

The download link for the those:
https://www.microsoft.com/net/download/visual-studio-sdks

Another part that's missing from the doc is that you need the "Developer Pack" for the .NET Framework version that matches the version of your project, which depends on your Unity version. You can find out what version your project targets by opening up your project's `Assembly-CSharp.csproj` file in a text editor and checking value of the `TargetFrameworkVersion` property.

> * Add links to help users investigate issues like IntelliSense not working. For example, checking the Omnisharp output channel may be helpful

So true, I think I would've been completely lost on why code completion was not working if not for this Omnishap error hinting that my project needed the "Developer Pack" for .NET Framework `v4.7.1` instead of the `v4.6` as instructed by the doc.

```
[fail]: OmniSharp.MSBuild.ProjectLoader
        The reference assemblies for framework ".NETFramework,Version=v4.7.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
```

**Comment by gregvanl** [comment]
Closing old issue with few upvotes. 
We can reopen if there is community interest ('help wanted' label) to review and update the Unity documentation as this issue contains lots of good notes and feedback.
The page ranks #62 in total pageviews with 18K views in Jan 2021.
