### ISSUE TITLE
Create custom language support in Visual Studio Code

### ISSUE THREAD

**Issue by adriatic** [Microsoft/vscode-docs#279]
So far, I only found **[this stackoverflow document](http://stackoverflow.com/questions/30687783/create-custom-language-in-visual-studio-code)** which is less detail oriented than I hoped for. 

I would like to add the support for Aurelia - any information about an existing effort in this direction or a document describing the creation of a language extension would be quite appreciated.

**Comment by gregvanl** [comment]
Hi Nikolaj,
Have you looked at the Extensibility topics on our website http://code.visualstudio.com?  Since the SO article you referenced, we have released our public extensibility model (November 2015). Take a look at the topics under the Extensions and Extensibility Reference sections.  For simple language support, we allow you to reuse existing TextMate .tmLanguage files as described in http://code.visualstudio.com/docs/customization/colorizer. The Go language extension is a great example of full language support and is open source at https://github.com/Microsoft/vscode-go.
Feel free to reactivate this issue if you don't find what you need.
- Greg

**Comment by gregvanl** [comment]
http://code.visualstudio.com/docs/extensions/overview
https://code.visualstudio.com/docs/extensionAPI/overview

**Comment by adriatic** [comment]
Thank you Greg - both references seem like a great start towards what I would like to achieve. As I know nothing about Go, at the moment I am not sure whether the Go language extension would take me to the point where I could do a similar job for Aurelia. That however is to soon to discuss, so I hope you will advise me when and if such time comes :-)

Regards,

Nik
