### ISSUE TITLE
Documentation edit link results in a 404

### ISSUE THREAD

**Issue by dnicolson** [microsoft/vscode-docs#2857]
Steps to Reproduce:

1. Navigate to https://code.visualstudio.com/api/references/vscode-api
2. Click the `Edit` button

Also, when expanding text items there is a height calculation problem during the animation, resulting in a noticeable jump:

![giphy](https://user-images.githubusercontent.com/2276355/58439359-e03c1700-80d3-11e9-8cde-7af6547f5709.gif)

**Comment by gregvanl** [comment]
Hi @dnicolson The API reference is auto-generated from vscode.d.ts so the fix now takes you to https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts.
For your second issue, I'll just link this to https://github.com/microsoft/vscode-docs/issues/1939 since there are multiple issues with this page. Thanks.
