### ISSUE TITLE
Not seeing Python: Flask (0.11.x or later) in debug configuration drop-down list

### ISSUE THREAD

**Issue by g2github** [microsoft/vscode-docs#2993]
I am seeing Python: Flask, but then debug session results differ from the tutorial (I get to the breakpoint, but then when I step over, the debugger doesnt stop at the next line of code (runs to completion...  Am I doing something wrong, or...?

**Comment by kraigb** [comment]
@g2github Yes, the docs are slightly out of date as the name of the configuration changed (as did the Debug icon). However, the Flask debugging config should work the same way. Are you sure you used the Step Over command (F10) and not Continue (F5)? If you are using Step Over but seeing Continue behavior, then try setting another breakpoint to see if that gets hit. If not, then there's perhaps a bug somewhere.

**Comment by g2github** [comment]
Thanks @kraigb.  Being very familiar with software debuggers from other IDE's, and I did follow the steps that you describe.  Only then did I ask the question here.  Should I file a bug report?

**Comment by JoshuaPartlow** [comment]
@anapo14 - could you comment on if this should be opened as a bug?

**Comment by luabud** [comment]
@g2github I'm so sorry that I missed this. I believe this was due to a bug we had in the August release, but it should be fixed now. Would you mind verifying if you still see that issue? If so, please do [file an issue in the Python extension repo](https://github.com/microsoft/vscode-python/issues/new?labels=classify%2C+type-bug&template=2_bug_report.md) so we can investigate further. Thank you!

**Comment by gregvanl** [comment]
Closing as an external issue with the Python extension. Please reopen if you think there is a documentation issue.
