### ISSUE TITLE
Is readthedocs up-to-date?

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode-docs#3003]
I was reading this doc
https://vscode-docs.readthedocs.io/en/stable/extensions/install-extension/

They say the following:
> Simply install using the VS Code command line providing the path to the .vsix file.

Which is absolutely not true (see https://github.com/Microsoft/vscode/issues/39276).

Is Microsoft owner of those pages? Are they out of date? If so, why are they online?

**Comment by gregvanl** [comment]
Hi @sguillia The content on readthedocs is quite out of date. For example the extensions and extensionAPI topics have moved to a /api node. Microsoft does not own or maintain those pages and I'm not sure why someone would go there instead of the official documentation at https://code.visualstudio.com/docs.

**Comment by sguillia** [comment]
Hi @gregvanl

> why someone would go there instead of the official documentation

Because I came across those pages while looking for docs about VSIX. Google still references it and I didn't knew they were out of date.

The pages come from here: https://github.com/ups216/vscode-docs

I understand you can't do much about it apart from contacting them. Thanks for quick answer!

**Comment by gregvanl** [comment]
Thanks @sguillia, I was curious if readthedocs had some features that were missing from the VS Code website :-).
