### ISSUE TITLE
executeDocumentSymbolProvider documentation not clear

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode-docs#3022]
To me, the documentation of `executeDocumentSymbolProvider` is missing information. ([link](https://code.visualstudio.com/api/references/commands))

> A promise that resolves to an array of SymbolInformation and DocumentSymbol instances.

Is it an array of, sometimes SymbolInformation, sometimes DocumentSymbol?

If so, how can I know this at runtime, since Typescript doesn't keep the type names?

Or is it an array of only SymbolInformation, or only DocumentSymbol, depending on the language provider?

Or is it some fun object like a merge between both (seems to be the case in [this unit test](https://github.com/microsoft/vscode/blob/bf3779f18f8d49818f0a75bdeb78f6ce2cc97ce5/src/vs/workbench/api/common/extHostApiCommands.ts#L458))? Is it always merged then, or again does it depend on the language provider? Why not a unique object?

There is no example of that command in [vscode-extension-samples](https://github.com/microsoft/vscode-extension-samples/search?q=executeDocumentSymbolProvider) so I can't guess there.

Can you please document this?
Thank you!

**Comment by jrieken** [comment]
> Or is it some fun object like a merge between both (seems to be the case in this unit test)? Is it always merged then

That. Some providers return SymbolInformation, some return DocumentSymbol instances. Since the result of calling this command is a merger of all provider and since internal document symbols (hierarchy) are inferred from symbol information (no hierarchy) we return an object that makes consumer of symbol information and document symbol happy.
