### ISSUE TITLE
Explanation on vscode.workspace.fs is not accurate and misleading

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode-docs#3059]
[Explanation](https://code.visualstudio.com/updates/v1_37#_vscodeworkspacefs) on `vscode.workspace.fs` in the release note  of July 2019  is not accurate. 

> it allows access to files from contributed file systems, such as the SSH or WSL remote file systems.

I am not sure what WSL remote file system means. The SSH remote file system must be [vscode-sshfs](https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs). Is there any VS Code extension providing WSL remote file system?

> Call to Action: If your extension is currently using the fs module from Node.js, consider migrating to the new vscode.workspace.fs API.

It seems for you to request extension authors to replace every single usage of the fs module with `vscode.workspace.fs`. I think you don't request that, in fact. Right? I would like you to clarify what type of usage of the module should be replaced with the new one.

**Comment by gregvanl** [comment]
Hi @tamuratak, the vscode.workspace.fs allows decoupling from an on-disk file system to one coming from a VS Code API file system provider, which might support remote files on another machine or any type of arbitrary file system. The explanation in the earlier release notes may be helpful https://code.visualstudio.com/updates/v1_36#_vscodeworkspacefs.
VS Code would like extension authors to switch over to vscode.workspace.fs so that their extensions continue to work in VS Code remote development scenarios https://code.visualstudio.com/docs/remote/remote-overview such as when connecting to remote machines over SSH or running within WSL.
