### ISSUE TITLE
Open Integrated Terminal at the Directory of the Currently Focused File

### ISSUE THREAD

**Issue by JosephTLyons** [microsoft/vscode-docs#3135]
It would be nice if there was an option to open the integrated terminal in the folder that currently contains the file you are working on.  Most of the time, this is where I would prefer to be placed.

I used Atom for many years and there was [a package available to do just this](https://atom.io/packages/open-terminal-here).  It would be awesome if this was a built-in feature for VS Code, as setting for the integrated terminal.

If this feature actually exists and I somehow missed it, or if someone knows how to do it currently, I would greatly appreciate hearing about it.

**Comment by gregvanl** [comment]
https://code.visualstudio.com/docs/editor/integrated-terminal#_using-variables has an example of setting the current working directory with the current file directory.

```json
    "terminal.integrated.cwd": "${fileDirname}"
```

Will that setting configuration do what you want?

**Comment by JosephTLyons** [comment]
@gregvanl, actually, that is absolutely perfect!  Thank you very much!  I noticed that that setting was there, but I didn't realize you could pass it variables.  I made the bad assumption that it would need to be a static location.

I suppose I have one other question... is it possible to apply this setting when launching an external terminal?  I'm on macOS... that setting you suggested works flawlessly when launching the integrated terminal (which is all I asked for), but I can't seem to get it to work when launching the external Terminal app from VS Code.

I'm going to close this because you did solve my issue.  Thank you.

**Comment by gregvanl** [comment]
@JosephTLyons Glad that works for you.
For launching the current file location in an external terminal, try the **Reveal in Explorer/Terminal** command available in the Command Palette and the file tabbed header context menu.

**Comment by gregvanl** [comment]
For your initial question, check out https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_39.md#open-new-terminals-with-custom-working-directories coming in the 1.39 release.

**Comment by JosephTLyons** [comment]
> @JosephTLyons Glad that works for you.
> For launching the current file location in an external terminal, try the **Reveal in Explorer/Terminal** command available in the Command Palette and the file tabbed header context menu.

I'm only seeing a "Reveal in Explorer" command in the command palette, but no option related to a Terminal.

**Comment by gregvanl** [comment]
The command is in the context menu on the file header up on the title bar.

![image](https://user-images.githubusercontent.com/12818376/66412379-42722600-e9aa-11e9-944c-10ba343a381c.png)

**Comment by JosephTLyons** [comment]
Right, that opens up the eternal file manager, such as Finder on Mac or File Explorer on Windows, but I was trying to launch an external terminal at the location of the file (such as launching Mac's Terminal app at the location of the current file).

**Comment by gregvanl** [comment]
Oh, got it. 
You can change the Terminal: Explorer Kind setting to 'external' and this will open an external terminal when you right-click on a file in the File Explorer and run "Open in Terminal".

**Comment by JosephTLyons** [comment]
Oh ok.  This is a bit strange.  

- I can launch an integrated terminal at the current files path with the command palette.  
- I can launch an external terminal at the current files path by right clicking the file as you mentioned above, but 
- I don't think I can launch an external terminal at the current path's file with the command palette.  

If I try to launch an external terminal via the command palette, it always resorts to the root of the project.  Ideally, both the integrated terminal and the external terminal could launch to the current file's directory directly from the command palette.  Is this possible?  That should be the last of my questions.  If I can launch an external terminal via the command palette and have it show up in the current files directory, that would be perfect, but I haven't been able to find a way to do this yet.

**Comment by gregvanl** [comment]
Hi @JosephTLyons Sorry for the delay in getting back to you. You should be able to bind a keyboard shortcut to the openInTerminal command.

![image](https://user-images.githubusercontent.com/12818376/67245424-c5ff2e80-f410-11e9-9b20-0c5b0f516d9f.png)

If you also have Terminal: Explorer Kind set to "external", then the keyboard shortcut (Ctrl+J, Ctrl+H) in the example above will open the current file in an external terminal.

**Comment by carehart** [comment]
I know this is an old discussion, but in case someone finds it surfaced by search/ai (as I did today), I will point out that while the problem remains there are a couple of solutions not discussed here (last in 2019, nor since). 

1 - First, to restate what Joseph originally posed (especially for the sake of current participants who may get notified out of the blue), we're talking about if you use vs code's `terminal: create new terminal`.  While that opens to the folder of the _current folder/workspace you have open_,  one concern is that _if you've opened a file in a subfolder of that_, it doesn't open to _that_ subfolder (of the file currently selected).  

The same is true _if you may have opened a file in vscode from the OS_ (which may not be in that selected folder/workspace at all).  And if you have no "folder" opened at all in vscode (in that case), then the new internal terminal opens instead to your current user directory--aagin, not the folder of the file currently selected.

2 -So what are some simple solutions? 

2.a - One is to use `open new external terminal`. While that will open a terminal OUTSIDE of vscode, it WILL at least open to the folder of the currently edited file. It's also available as a built-in shortcut, such as `ctrl+shift+c`. (It is indeed odd that IT will open to the expected folder, but `create new terminal` will not.

2.b - As for opening VSCode's INTERNAL terminal (to the current folder of an edited file), that still seems unsupported by vscode (in 2026), though some tedious workaround steps may be found. But there have been various extensions that offer to do this one simple job.

And one that's working for me in 2026 is "Terminal Here". While the code's not changed for several years, it does the job, via its command `terminal here: create terminal`, which WILL open the internal terminal to the folder of the currently edited file. Lamentable that it takes such an extension, but the source is very simple to assess, [a single 33-line file here](https://github.com/Tyriar/vscode-terminal-here/tree/master/src).

Apologies if anyone is offended by my hijacking/resurrecting a "dead thread". I'm not reopening the issue. I'm just adding the comment as some resources point to this as an authoritative discussion of this topic. It lacked these couple of alternative solutions, and I hoped they may help future readers. And of course if I've missed or misrepresented anything, I welcome correction/feedback.
