### ISSUE TITLE
Python debugging docs don't mention "module" argument to launch.json

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-docs#3251]
Basically https://code.visualstudio.com/docs/python/debugging doesn't cover the details necessary for someone to reconstruct the "Python: Module" configuration.

/cc @microsoft/pyvsc

**Comment by JoshuaPartlow** [comment]
@brettcannon - Just to be sure, is this just adding the module argument to the docs and calling out that it should be set to the name of the module (as a string) when you want to create a configuration for debugging a module? Or is there more? Thanks.

**Comment by brettcannon** [comment]
@JoshuaPartlow correct.

**Comment by int19h** [comment]
Do we have docs for "code"?

**Comment by brettcannon** [comment]
@int19h docs for debugging are at https://code.visualstudio.com/docs/python/debugging and I didn't see any mention of "code".

**Comment by int19h** [comment]
Probably because we never had any default launch configs for it. The feature is basically that `"code": ...` translates to `python -c ...`, just like `"module": ...`  translates to `python -m ...`, and `"program": ...` is just `python ...`.

BTW, it might be worthwhile mentioning these equivalences when documenting all three, because that way we can refer the users to Python's own docs on the exact meanings of the values (including search paths etc); the debugger makes considerable effort to e.g. make "module" behave identically for this exact purpose.

**Comment by JoshuaPartlow** [comment]
Addressed "module" with above PR.
