### ISSUE TITLE
Parameter hints not working (Python)

### ISSUE THREAD

**Issue by imanimufti** [microsoft/vscode-docs#3333]
I can't see the parameter hints in VS Code. Ctrl + Shift + Space does nothing. 

In addition I also have this error
`Jupyter kernel cannot be started from 'Python 3.8.1 32-bit'. Using closest match Python 3.7.4 64-bit ('base': conda) instead. Error starting original kernel: Error: Module 'notebook' not installed.`

Everything works fine and I can run code. But I can't trigger parameter hints or use the intellisense feature when running code in a python script format. When I use the jupyter notebook cells format, the intellisense feature works but the paramter hints still dont work.

I've tried everything in all the other threads similar to this. Someone please help me. I've been stuck on this for two days now. I'm new to VS Code.

**Comment by greazer** [comment]
Hi @imanimufti, sorry for the trouble you're having! To help narrow down the situation you find yourself in, can you let us know whether you don't get intellisense _before_ running code in the interactive window? 

Also, does the same problem occur for a very simple, but separate, project like: 

import os
print(os.

Where on pressing '.' after "os" you get nothing?

Also, let us know the state of the "Python: Jedi Enabled" setting in VS Code. If it's checked, try unchecking to see if your problem is resolved. Eventually, this setting WILL be unchecked by default in the Python extension so keeping it unchecked all the time, is ok.

**Comment by gregvanl** [comment]
Closing as no response from user.

**Comment by carlschmidt26** [comment]
Just in case somybody comes across this issue.
I had a similar problem and it seems that some methods are supported with default settings (e.g. `np.sum`) while other are not (e.g. `np.exp` or `np.array`).

What worked for me was adding `"python.languageServer": "Pylance",` in `settings.json`.
Source: [https://stackoverflow.com/questions/64680361/vscode-autocompletion-doesnt-work-for-jupyter-notebook](https://stackoverflow.com/questions/64680361/vscode-autocompletion-doesnt-work-for-jupyter-notebook)

**Comment by wconnell** [comment]
I am having this issue. Intellisense pops up for e.g. numpy methods - no parameter hints though.

**Comment by namespace-Pt** [comment]
@wconnell how do you solve it?
