### ISSUE TITLE
The editor is not working properly as it was doing before

### ISSUE THREAD

**Issue by KASH-IT** [microsoft/vscode-docs#3364]
After a few PHP scripts I decided to write some HTML codes but then I experienced that the the editor was reading and reacting to the HTML files like the PHP ones, and the was reacting the same to the PHP ones..... it was reacting to the .PHP files like both HTML's files and PHP's files..... It was not a major issue untill I viewed that I would need the help of a server to see my .PHP cum .HTML file. And then I returned to code .HTML files it was not reacting to it like .HTML but still I could view the result in the browser, but still without inteli-sense of the Software it was very difficult and lengthy to wright 5 lines of code

**Comment by gregvanl** [comment]
Hi @KASH-IT This looks like a VS Code product issue rather than a documentation issue. If you have reproducible steps or a sample project showing the issue, you can open an issue in the VS Code product repository https://github.com/microsoft/vscode/issues. Another option is to post a question on Stack Overflow https://stackoverflow.com/questions/tagged/visual-studio-code
