### ISSUE TITLE
For Docker SSH scenarios, using an SSH tunnel is no longer necessary

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docs#3399]
Beginning in version 0.9.0 of the Docker extension we added proper SSH support, so it is [no longer necessary to use an SSH tunnel to connect](https://github.com/microsoft/vscode-docs/blob/master/docs/remote/troubleshooting.md#using-an-ssh-tunnel-to-connect-to-a-remote-docker-host). Instead, users can directly set the `DOCKER_HOST` environment variable or `docker.host` VSCode setting to the appropriate `ssh://user@host` URL. It is still necessary to set up agent authentication. More information on our wiki: https://github.com/microsoft/vscode-docker/wiki/SSH#directly-via-ssh

**Comment by gregvanl** [comment]
@bwateratmsft It looks like this is already covered in the section https://code.visualstudio.com/docs/containers/ssh#_directly-via-ssh which was ported from the wiki.
Are there more updates required?

**Comment by bwateratmsft** [comment]
Ah, I wasn't aware that'd gotten moved into the docs (bear with me, been on parental leave 😄). Anyway, could we link to that SSH setup doc from here: https://github.com/microsoft/vscode-docs/blob/master/docs/remote/troubleshooting.md#using-an-ssh-tunnel-to-connect-to-a-remote-docker-host

And also, probably downplay the tunnel approach, as it isn't needed anymore and isn't the "preferred" way?

**Comment by bwateratmsft** [comment]
@Chuxel What do you think about reducing or perhaps even removing that section about SSH tunneling? Or at least linking back to our [doc](https://code.visualstudio.com/docs/containers/ssh)? Using a tunnel isn't strictly necessary anymore and somewhat less "preferred" compared to directly configuring `DOCKER_HOST` (or `docker.host`) to an `ssh://...` value.

**Comment by ghogen** [comment]
@bwateratmsft @Chuxel @gregvanl The doc says "However, you may run into situations where this [simple SSH method] does not work in your environment due to SSH configuration complexity or other limitations. In this case, an SSH tunnel can be used as a fallback."

I was about to add a link back to the SSH [doc](https://code.visualstudio.com/docs/containers/ssh) but as for removing the SSH tunneling section, what about those situations discussed here where configuration is more complex? Are there real scenarios for tunneling?

**Comment by bwateratmsft** [comment]
I would say yes. Given the near infinite ways to connect to a remote machine I'm sure there are users who must use an SSH tunnel.

So as I think about it more, removing the section about tunneling is not the right approach. But, we should definitely link back to the other doc at a minimum--maybe a quick subsection with a link, above the tunneling section?

**Comment by Chuxel** [comment]
@ghogen @bwateratmsft Yes, this is a troubleshooting section for the main article which references the `ssh://` URI along with other information: https://github.com/microsoft/vscode-docs/blob/master/docs/remote/containers-advanced.md#developing-inside-a-container-on-a-remote-docker-host

The problem is `dockerode` doesn't support everything SSH or even the Docker CLI supports right now, so I actually had a request to add it back in as an option.  It's not as best practice which is why I removed it from that main section.

**Comment by ghogen** [comment]
@Chuxel @bwateratmsft @gregvanl  I have a PR #3400 started which adds the link and changes the heading for that troubleshooting node to de-emphasize tunneling, but keeps the section.  Feel free to suggest changes.

**Comment by bwateratmsft** [comment]
@ghogen Looks perfect to me, thanks!

**Comment by bwateratmsft** [comment]
Discussed with @Chuxel in [this thread](https://github.com/microsoft/vscode-docs/pull/3400#discussion_r378534363), since Remote - Containers also can take advantage of `docker.host`, and since those docs also treat tunneling as the less-preferred path, I'm fine with won't-fixing this issue. Eventually we should revisit and consolidate documentation across Remote - Containers, Remote - SSH, and Docker, but that belongs in a different issue.
