### ISSUE TITLE
Update ThemeIcon docs to show codicon example

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-docs#3442]
https://code.visualstudio.com/api/references/vscode-api#ThemeIcon

> Note that theme icons can also be rendered inside labels and descriptions. Places that support theme icons spell this out and they use the $(<name>)-syntax, for instance quickPick.label = "Hello World $(globe)".

We currently show examples where you can embed icons inside of labels but we don't show examples for using this using `ThemeIcon`. We should also make another note below this that you can use icons via `new ThemeIcon('<name>')` as well.

**Comment by gregvanl** [comment]
This change would need to be made in vscode.d.ts in the vscode repo since the API reference is generated from that file. 
I'm not sure we need to document `new ThemeIcon('name')` since this is covered in the constructor. 

![image](https://user-images.githubusercontent.com/12818376/77198749-d6d9cc00-6aa4-11ea-8a91-2ee1f9d22191.png)
