### ISSUE TITLE
Can't see HelloWorld variables value in debug

### ISSUE THREAD

**Issue by Clonimus74** [microsoft/vscode-docs#3451]
Hi,

I've setup VSCode C++ compiler according to [this guide](https://code.visualstudio.com/docs/cpp/config-mingw).
When I put msg or word variables in the watch, their value is no displayed.
You can see the pic here - https://ibb.co/cDgtkPp
Any ideas?

Edit:
I tried a different code. I can see values of int in the debugger, but not values of string, arrays and vectors.

**Comment by Clonimus74** [comment]
Anyone?

**Comment by gregvanl** [comment]
Hi @Clonimus74 Sorry for the delay. Here's what the C++ extension engineering team has to say:

"Those are because the user doesn’t have pretty printers installed within their gdb.
Their types are “std::” types and the extension relies on gdb to provide the correct way to visualize the data. 

Here are some links that might help:
https://stackoverflow.com/questions/11606048/how-to-pretty-print-stl-containers-in-gdb
https://codeyarns.com/2014/07/17/how-to-enable-pretty-printing-for-stl-in-gdb/

The problem with MinGW is that acquiring the pretty printers from the installer is hard.

https://stackoverflow.com/questions/4985414/how-to-enable-gdb-pretty-printing-for-c-stl-objects-in-eclipse-cdt

The third comment explains that you need to install gdb-python within the MINGW installer to get the pretty printers."

**Comment by Clonimus74** [comment]
Thanks, but I can't seem to make work.
I use window 7

**Comment by gregvanl** [comment]
Were you able to go through MinGW’s configuration tool and find/install gdb-python? That is what the engineering team recommends.

**Comment by gregvanl** [comment]
Hi @Clonimus74 Here are the instructions for installing Python, which is required for the C++ pretty printer, and registering the pretty printer:

If you don't have python GDB, open a shell/command and use MinGW-get.exe to 'install' Python-enabled GDB e.g.
   MinGw-get.exe install gdb-python
1a) Get Python 2.7.x from http://python.org/download/ and install
1b) Make sure PYTHONPATH and PYTHONHOME are set in your environment:
 PYTHONPATH should be C:\Python27\Lib   (or similar)
 PYTHONHOME should be C:\Python27
1c) Add PYTHONHOME to your PATH
 %PYTHONHOME%;...
2a) Open a text enter, enter the following statements. Notice the 3rd line is pointing to where the python scripts are located. See notes below about this!
python
import sys
sys.path.insert(0, 'C:/MinGW/share/gcc-4.6.1/python')         
from libstdcxx.v6.printers import register_libstdcxx_printers
register_libstdcxx_printers (None)
end
2b) Save as '.gdbinit' NOTE: Windows explorer will not let you name a file that starts with with a period from explorer. Most text edits (including Notepad) will let you. GDB init files are like 'scripts' of GDB commands that GBD will execute upon loading.
2c) The '.gdbinit' file needs to be in the working directory of GDB (most likely this is your projects root directory but your IDE can tell you.

**Comment by Clonimus74** [comment]
Thank you very much

**Comment by gregvanl** [comment]
Hi @Clonimus74 I'm glad you're unblocked. 
Were you able to get pretty printing installed and registered and now you see Watch panel variable values?
If so and you used the steps in the earlier comment, were there any steps that were confusing?

**Comment by Clonimus74** [comment]
The instructions are very clear, thank you.
I assume it would have worked as some of these steps weren't as clear in other links.
As I was in a hurry I uninstalled MinGW and installed Visual Studio Tools.
