### ISSUE TITLE
Node Quickstart Doesn't Work as Described on Windows

### ISSUE THREAD

**Issue by davidshq** [microsoft/vscode-docs#3497]
Appears [this page is a little outdated](https://code.visualstudio.com/docs/containers/quickstart-node).

If one follows the instructions (at least on Windows 10) the [image will not be created](https://github.com/microsoft/vscode-docker/issues/1462), it fails silently. The tasks.json file has to be edited manually and docker-build changed from workspaceFolder to fileDirName

Once the image is built, the debug configuration is called "Docker Node.js Launch", "and Attach" is no longer part of the config name.

This will fail with a timeout, this is because the container is not started automatically when one debugs. Instructions need to explicitly add process of starting container here (earlier we are told to start it but then stop it and never instructed to turn on again).

If we run debug again with the container up we will get another error - this time being informed that [version has not been set in our tasks.json](https://github.com/microsoft/vscode/issues/91911). This doesn't stop one from debugging, it is just confusing.

Once this is done we'll get a Cannot connect runtime process, timeout after 10000 ms...this last one I haven't figured out yet.

**Comment by philliphoff** [comment]
@davidshq Thanks for the feedback!

> If one follows the instructions (at least on Windows 10) the image will not be created, it fails silently. The tasks.json file has to be edited manually and docker-build changed from workspaceFolder to fileDirName

I'm not seeing this when I run through the Quickstart on Windows 10 (with the latest VS Code, Docker extension, WSL2 and Docker Desktop).  The image is created successfully with no changes needed to the `tasks.json`.  Would you be able to attach a copy of your workspace folder that exhibits the issue?

> Once the image is built, the debug configuration is called "Docker Node.js Launch", "and Attach" is no longer part of the config name.

This is true; in 1.0 the names of the generated configurations were tweaked to be more consistent across the supported stacks (i.e. Node.js, .NET Core, and Python).  We should update the docs to match.

> This will fail with a timeout, this is because the container is not started automatically when one debugs. Instructions need to explicitly add process of starting container here (earlier we are told to start it but then stop it and never instructed to turn on again).

I'm not seeing this either; the configuration in `launch.json` *should* be linked to the Docker run task in `tasks.json` so that the container is started before debugging begins.  (This is what happens when I F5.  Again, it would be great the workspace to understand what might have happened.)

> If we run debug again with the container up we will get another error - this time being informed that version has not been set in our tasks.json. This doesn't stop one from debugging, it is just confusing.

Agreed, the warning can be confusing.  VS Code doesn't properly add the `version` property to `tasks.json` when extensions (such as the Docker extension) adds an initial set of tasks.  However, it's been fixed and should show up in an upcoming release of VS Code.

> Once this is done we'll get a Cannot connect runtime process, timeout after 10000 ms...this last one I haven't figured out yet.

This is different than what I see on my machine (a successful debugging session).  If you are able to provide the workspace you created and maybe some other details, such as the VS Code version, Docker extension version, Docker version, and Windows version, it would help us understand this difference and ensure our docs are up to date. Thanks!

@ghogen One other thing I noticed: steps (1) and (2) in the [Debug in the service container](https://code.visualstudio.com/docs/containers/quickstart-node#_debug-in-the-service-container) section are no longer required with 1.0 of the Docker extension.  (The extension now looks through both the debug console and the Docker logs for application output, so forcing logs to the debug console is no longer necessary, though has no impact either way.)

**Comment by ghogen** [comment]
@philliphoff can you review?

**Comment by davidshq** [comment]
@philliphoff Unfortunately, after submitting this ticket I decided it was time to refresh my machine (oops). I'm working on setting up a Windows 10 VM with essentially the same settings I had previously to run through this article again and see if the same issues arise...will be a little as I have to reinstall all the tooling.

**Comment by gregvanl** [comment]
Closing as documentation was updated. Please reopen if you can reproduce the other issues.
