### ISSUE TITLE
is:issue is:open vs code debugging bar c++ not moving (multiple files) on mac

### ISSUE THREAD

**Issue by azedede** [microsoft/vscode-docs#3650]
the debug launch but stepping not moving
<img width="876" alt="Screen Shot 2020-05-06 at 11 29 49 PM" src="https://user-images.githubusercontent.com/15974184/81251618-b2549780-8ff1-11ea-8736-a82650b87c2e.png">
<img width="867" alt="Screen Shot 2020-05-06 at 11 30 28 PM" src="https://user-images.githubusercontent.com/15974184/81251619-b385c480-8ff1-11ea-9bc2-0e4454b9f5f7.png">
<img width="852" alt="Screen Shot 2020-05-06 at 11 31 02 PM" src="https://user-images.githubusercontent.com/15974184/81251620-b385c480-8ff1-11ea-892a-c201928440f1.png">

**Comment by gregvanl** [comment]
Hi @azedede Can you provide the macOS, VS Code, and C++ extension versions you are using?
And are you saying that Step Over (F10_ or Continue (F5) aren't working for you?

**Comment by gregvanl** [comment]
Hi @azedede This looks like a C++ extension issue rather than a documentation issue so could you port the issue to https://github.com/microsoft/vscode-cpptools/issues. Engineers monitoring that repo should be able to help.

You can also enable logging of debugger requests if you add the following to your launch.json:

```json
“logging”: {
   “engineLogging”: true
}
```

**Comment by gregvanl** [comment]
Recommendation is to open an issue in the C++ extension repository.
