### ISSUE TITLE
the vscode open version 

### ISSUE THREAD

**Issue by SinorStark** [microsoft/vscode-docs#3651]
i have the latest vs code(1.44.2). However, each time i opened it, the version is 1.38.1. Only can i chose 'check for update' and 'restart it' can solve this problem. I wanna to know how to get the latest version directly when i opened it?

**Comment by gregvanl** [comment]
Hi @SinorStark What platform are you running on and which version would you like to install?
Most platforms update VS Code in the background and rely on you to restart VS Code to move to the latest version.

**Comment by SinorStark** [comment]
> Hi @SinorStark What platform are you running on and which version would you like to install?
> Most platforms update VS Code in the background and rely on you to restart VS Code to move to the latest version.

I am running on windows. I want use the latest VS Code version. And I have to use the latest after I opened it and check for update and restart to update.

**Comment by gregvanl** [comment]
@SinorStark Thank you for responding. Does this mean you are unblocked and using the latest version is what you want to do?
You can also disable updates if you'd like to stay with a specific version. https://code.visualstudio.com/docs/supporting/faq#_how-do-i-opt-out-of-vs-code-autoupdates
Or perhaps you have set Update: Mode to 'manual' which is why you need to **Check for Updates** in order to get the latest version to download. 
Can you check if "update.mode" in user settings is set to 'manual' or 'none'?

**Comment by gregvanl** [comment]
No reply. Closing
