### ISSUE TITLE
code folding

### ISSUE THREAD

**Issue by Azadpurbey** [microsoft/vscode-docs#3676]
Coding folding not works with #include in C++

**Comment by gregvanl** [comment]
Hi @Azadpurbey For advanced code folding to work, you need to install the [C/C++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) so that there is a language server running, which understands that C++ #include regions can be folded.

Here's a screen shot with the C/C++ extension installed.

![image](https://user-images.githubusercontent.com/12818376/82271287-3bda6280-992c-11ea-8008-f9665b447a25.png)

and collapsed

![image](https://user-images.githubusercontent.com/12818376/82271396-8065fe00-992c-11ea-84a5-2b962c8c2480.png)
