### ISSUE TITLE
Please help me, I don't want to give up;About ADD tasks.json file

### ISSUE THREAD

**Issue by ZhouJian12345678** [microsoft/vscode-docs#3724]
Add tasks.json file, no c / c ++: g ++ build activity file,appear shell:g ++ build activity file and many more shell file; I hope you can answer my doubts, thank you!

**Comment by gregvanl** [comment]
Hi @ZhouJian12345678 Do you have the Microsoft C/C++ extensions installed? That extension should provide the necessary g++ build tasks.
What other extensions do you have installed? 
Can you provide the list of extension IDs by running `code --list-extensions`  from a command prompt or terminal?

**Comment by ZhouJian12345678** [comment]
I only have the C/C++extensions installed ，I'm now using a 1.41 version of Vscode



发自我的iPhone


------------------ Original ------------------

**Comment by gregvanl** [comment]
@ZhouJian12345678 That is a fairly old version of VS Code. Have you tried updating to 1.45.1?

Can you provide a screen shot of what you are seeing? Are you seeing "shell:g++" in the **Configure Default Build Task** dropdown?

**Comment by ZhouJian12345678** [comment]
Yes，I see the&nbsp;&nbsp;"shell:g++" in the&nbsp;Configure Default Build Task&nbsp;dropdown。I wouldn't have done it, unlike what the website provides，so I give up the new version。



发自我的iPhone


------------------ Original ------------------

**Comment by gregvanl** [comment]
OK, I see this too.

![image](https://user-images.githubusercontent.com/12818376/83222785-0e609680-a12e-11ea-9705-901a671509aa.png)

This looks like a recent change to the C/C++ extension and I'll need to contact the extension team to see if this was intentional. I don't know why they would have put a "shell: " prefix.

You should be able to select "shell: g++ build active file".

Thanks for pointing this out.

**Comment by sean-mcmanus** [comment]
It's a regression from 0.28.1 -- we should have a fix in our next release: https://github.com/microsoft/vscode-cpptools/pull/5585

**Comment by ZhouJian12345678** [comment]
About reusing our C++ configuration ，just copy the JSON files to a .vscode folder in a new project folder （workspace）。How do I set the default vscode JSON files？ Is there a way to generate a file with an instruction next time？



发自我的iPhone


------------------ Original ------------------

**Comment by sean-mcmanus** [comment]
@ZhouJian12345678 Using the C/C++: Edit Configuration command can generate a default c_cpp_properties.json file. You could also set the settings that will get used if no c_cpp_properties.json exists via the C_Cpp.default.* settings.

**Comment by ZhouJian12345678** [comment]
Thanks ！



发自我的iPhone


------------------ Original ------------------

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/0.28.2 , but you might hit a new issue on Windows if the compiler path isn't in your path (https://github.com/microsoft/vscode-cpptools/issues/5604). You may also hit a VS Code issue at https://github.com/microsoft/vscode/issues/97891 , which is fixed with VS Code Insiders.
