### ISSUE TITLE
Document what exclude lists are relative to and how they combine

### ISSUE THREAD

**Issue by RalfJung** [microsoft/vscode-docs#3758]
By mere accident, I just figured out that the `files.exclude` patterns are interpreted relative to the workspace root. It would be good to have that documented. (Same for `search.exclude`.)

The docs also do not explain what happens when you have `files.exclude` set both globally and in a workspace. Do the two lists get concatenated in some way, or does one overwrite the other? (The same question also arises for `files.watcherExclude` and `search.exclude`.)

Finally, the settings docs do not say how the `true`/`false` can be used: do earlier or later list elements get precedence?

**Comment by gregvanl** [comment]
The default settings comments for `files.exclude`, `search.exclude` are generated from the settings descriptions in source in the product repo. PRs welcome if you'd like to add clarification to the comments.
Most VS Code setting paths are workspace relative.
Given that these settings are workspace relative, most people set these exclusions at the workspace level since the paths will depend on the workspace folder structure, and are unlikely to be shared globally through user settings.

**Comment by RalfJung** [comment]
@gregvanl thanks for the response!

> Given that these settings are workspace relative, most people set these exclusions at the workspace level since the paths will depend on the workspace folder structure, and are unlikely to be applicable globally through user settings.

I have `"**/target/**"` in my global `files.watcherExclude`, which makes a lot of sense to have globally since all Rust projects will want to have their `target` folder(s) ignored.

Unfortunately, the docs do not say what happens when I now also set `files.watcherExclude` per-workspace -- does that overwrite the global list or are the two combined in some way?

**Comment by gregvanl** [comment]
In general, workspace settings override user settings and this is at the individual glob pattern level for these types of settings.
It also looks like last entry in a glob pattern wins, to answer your question about duplicate entry order precedence.
