### ISSUE TITLE
New Contributor Questions

### ISSUE THREAD

**Issue by jhomme** [microsoft/vscode-docs#3781]
Do  I need to sync my forked repository with this one after I have forked it?

**Comment by gregvanl** [comment]
Hi @jhomme Looks like you worked out your question about forked repos since you submitted a PR.

If you have questions about forking, keeping your fork up to date with the upstream remote, and submitting PRs, you can consult the GitHub help docs. https://help.github.com/github/collaborating-with-issues-and-pull-requests/syncing-a-fork
