### ISSUE TITLE
Can't create my new migration repository.

### ISSUE THREAD

**Issue by Drex08x** [microsoft/vscode-docs#3878]
![errof](https://user-images.githubusercontent.com/68532100/87906620-9bfe9980-ca80-11ea-8623-1f2bb15eb994.PNG)

Tried everything but still getting this error !!!

**Comment by JoshuaPartlow** [comment]
Hi @Drex08x - The support here is for issues with the VS Code Python extension docs. It seems like your issue is outside of that scope. I haven't used `flask db init` before, but offhand it looks like you're setting the FLASK_APP environment variable correctly, so I'm not sure why you'd get that error message. Perhaps look over the related Flask/Flask-migrate docs to see if they offer any help.
