### ISSUE TITLE
[Python] Add a sentence to clarify how to install requirements.txt files 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-docs#3904]
This comes from this issue: https://github.com/microsoft/vscode-python/issues/13116

## Expected behaviour

Able to clone and run repo containing requirements.txt (but no env folder)

## Actual behaviour

Able to clone, but _slightly_ unclear how to create env on [this page](https://code.visualstudio.com/docs/python/environments).

## Steps to reproduce:

Through experimentation, I discovered you must pip install _having created an environment_, like this:

```
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
```
Then, open the file build_views_file.py, and run in (e.g, under the debugger).

We could add a sentence here(https://code.visualstudio.com/docs/python/environments) to say that if the project has a requirements.txt file, one can simply run `pip install -r requirements.txt`  in the activated terminal

**Comment by JoshuaPartlow** [comment]
Topic has an existing note in [this section](https://code.visualstudio.com/docs/python/environments#_global-virtual-and-conda-environments), so closing. If something more discoverable is desired, or I misunderstood, just reopen.

**Comment by jgwinner** [comment]
Hi. I stumbled here because the doc page doesn't make it clear how to load an existing environment, honestly.

It is true, the command is mentioned at the bottom of the page, but you have to wade through a lot of background. Again honestly, I sort of skimmed this because I know why to create a virtual environment. I do think the section is good though.

The use case is doing a git clone, then trying to edit an existing project. 

In fact, bing search showed me how much easier it is with Visual Studio 2019 :)

In any event, I think there needs to be a note right under the commands `py -3 -m venv .venv` to then run `pip install -r requirements.txt` as to do the one would quite often do the other. Then add a foot note or (see below for requirements.txt rationale)

OR have a summary at the bottom of the page showing both commands.

This is sort of a TLDR issue I guess :)  Again, it was sort of my mistake for not reading the entire section but that's a lot of background stuff to ingest. 

        == John ==

**Comment by jgwinner** [comment]
Oh - I almost forgot, I found out the hard way that the PS doesn't switch to the virtual environment, so I ended up adding a lot of stuff to my base. I'd recommend also adding:

`venv/Scripts/Activate.ps1`

Does that make sense?
