### ISSUE TITLE
contributes.breakpoints should also mention language service extensions

### ISSUE THREAD

**Issue by saschanaz** [microsoft/vscode-docs#3984]
[The documentation](https://code.visualstudio.com/api/references/contribution-points#contributes.breakpoints) says it's for debugger extensions, but I think it doesn't always make sense as [debuggers should not be required to know every language](https://code.visualstudio.com/api/references/contribution-points#contributes.breakpoints) that it supports. Wouldn't it be better if each language service extension listed their language as debuggable (https://github.com/rust-analyzer/rust-analyzer/issues/5952)?

**Comment by gregvanl** [comment]
Hi @saschanaz I'm not sure I understand your suggestion. For VS Code, language services and debuggers are specific for different programming languages. A debugger might support several related programming languages but it is a finite set. In addition, a language might be supported by several debuggers from different debugger providers.
This also looks more like a product or extension API issue, rather than a documentation issue. You can open issues about the Extension API in the product repository https://github.com/microsoft/vscode

**Comment by saschanaz** [comment]
>A debugger might support several related programming languages but it is a finite set.

I would say not exactly. For example, any language that can provide [PDB](https://github.com/Microsoft/microsoft-pdb) format can be debugged by ms-vscode.cpptools, and thus the list can be infinite. (Rust joined the party, for example.)

**Comment by saschanaz** [comment]
>This also looks more like a product or extension API issue

Does it mean language service extensions currently can't add `contributes.breakpoints` field?
