### ISSUE TITLE
Opening a Project: indicate that the C# extension is needed

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-docs#403]
Refs: https://code.visualstudio.com/docs/editor/codebasics#_opening-a-project

We seem to say that a C# context is indicated in the status bar. But that is only true if you have the C# extension installed. So we should mention this and provide a link how to install it if needed.

**Comment by gregvanl** [comment]
Remove the "Opening a Project" section from The Basics since only applicable to C# and it is covered in the C# topic https://code.visualstudio.com/docs/languages/csharp#_roslyn-and-omnisharp. Bringing up project context switching in codebasics.md will be confusing for new users many of whom will never see the OmniSharp flame.
