### ISSUE TITLE
Info about using custom emmet snippets is not working

### ISSUE THREAD

**Issue by TD540** [microsoft/vscode-docs#4053]
https://code.visualstudio.com/docs/editor/emmet#_using-custom-emmet-snippets

Either info is wrong or there's a bug in VSCode? Perhaps related to https://github.com/microsoft/vscode/issues/104962 ?

Using vscode 1.50.0 on macOS Catalina

**Comment by shurinskiy** [comment]
Hi guys! Does anyone even have this thing working? I am at a loss. Maybe I'm doing something wrong? I've reinstalled vscode several times and tried different ways of specifying the path to the snippet file. But no, the system has never been able to pick up. Several months have passed since the bug appeared and an endless number of updates.

**Comment by gregvanl** [comment]
@rzhao271 While you are investigating https://github.com/microsoft/vscode/issues/104962, if there are any workarounds, you can  respond here.

**Comment by gregvanl** [comment]
The product issue  https://github.com/microsoft/vscode/issues/104962 has been fixed and you can test it shortly with the Insiders build https://code.visualstudio.com/insiders.
