### ISSUE TITLE
Breadcrumb "when" clauses are not documented

### ISSUE THREAD

**Issue by macintacos** [microsoft/vscode-docs#4068]
I was trying to create some mappings specifically enabled only when breadcrumbs were focused/active, and realized that it's not mentioned anywhere here: https://github.com/microsoft/vscode-docs/blob/master/docs/getstarted/keybindings.md#when-clause-contexts

As far as I can tell, the available contexts are:

```
breadcrumbsActive
breadcrumbsVisible
breadcrumbsPossible
``` 

Not sure if there are any others. Thanks!

**Comment by gregvanl** [comment]
Hi @macintacos We don't list all available when clauses, since there are hundreds and many are specific to the VS Code UI and not generally useful for regular users.
Could you describe your scenario? Are you using the breadcrumbs when clause in an extension or a user set keybinding? Thanks

**Comment by macintacos** [comment]
Hi @gregvanl!

I was purely trying to create my own remapping for when the breadcrumbs had focus, but in order to figure that out, I needed to know the various `when` clauses so that it wouldn't interfere with something else that I have mapped. I have a pretty heavily remapped setup, so this is a common thing that I do.

It's unfortunate that most of the `when` clauses are undocumented, if I'm honest. I think that at a certain point I'm going to want to configure every inch of my VSCode setup, and I've found that referencing all of the `when` clauses is incredibly helpful in avoiding conflicts with other mappings that I've already set up.

This is almost certainly a pretty naive ask, but would it be possible to crawl the VSCode codebase and just pull out all of the `when` clause names themselves and just dump them in a file? I find that most of the `when` clauses' actual names are pretty self-explanatory, so I don't even think that it needs to have documentation for them, just a file with all of them to reference. Completely understand if that's a request to make in the VSCode repo proper, just let me know and I'll go ahead and open an issue there.

**Comment by gregvanl** [comment]
Hi @macintacos 
Have you looked at the default Keybinding JSON (opened with command Preferences: Open Default Keyboard Shortcuts (JSON))? That JSON file shows all the currently bound keyboard shortcuts and their conditional when clauses.
The Keyboard Shortcuts editor (Preferences: Open Keyboard Shortcuts) also lets you quickly search and filter on both command and when clause text.

![image](https://user-images.githubusercontent.com/12818376/96296937-f1c1df80-0fa4-11eb-947c-b0a018deacb7.png)

I don't mean to put you off and your request is certainly reasonable but we try to be careful to not overwhelm new users with too much information. If there are in-product ways for more advanced users to get information, we prefer that since it will always be up to date and reflect the current state of the user's editor (non-default settings, modifications by extensions, etc).

**Comment by macintacos** [comment]
Completely understand - I appreciate you pointing me in that direction. I had honestly forgotten about the default keyboard shortcuts JSON document - I had previously only been using the UI version of it to figure out `when` keybindings. The biggest issue I have with the GUI is that it cuts off some of the more complicated "when" clauses, but the JSON document should solve this completely. Thanks a bunch - I'll go ahead and close this out.

**Comment by gregvanl** [comment]
There was a mention about finding other when clause contexts via Default Keyboard Shortcuts but moved it up above the list to be more discoverable. Also mention Keyboard Shortcuts editor search and filtering.

https://github.com/microsoft/vscode-docs/commit/6f0a4f4b4b97bff547ccda99b54747c70baa1520

**Comment by macintacos** [comment]
Appreciate the pointer, and thanks for adding that to the documentation! I try to keep my mouse usage to be an minimal as possible, which is probably another reason why I didn't see it 🙂 but that's probably better feedback for the VSCode repo itself, so I'll open an issue there when I have time - IMO, it should just wrap the whole `when` clause in that view (or at least provide an option to do so).
