### ISSUE TITLE
“View:Show Explorer” command is disabled when I update to ver.1.51.0

### ISSUE THREAD

**Issue by lxnow321** [microsoft/vscode-docs#4118]
“View:Show Explorer” command is disabled when I update to ver.1.51.0, and the "Auto Reveal" is same too.

**Comment by gregvanl** [comment]
Hi @lxnow321 Where are you expecting View: Show Explorer that you don't see the command. I can see the command in the Command Palette:

![image](https://user-images.githubusercontent.com/12818376/98588555-b7d0ba00-2280-11eb-906c-1da2adde73ca.png)

The "Auto Reveal" settings also are available in the Settings editor:

![image](https://user-images.githubusercontent.com/12818376/98588994-712f8f80-2281-11eb-9a14-ed606d5e784a.png)

There was a new value added for Explorer: Auto Reveal, `focusNoScroll`, with the 1.46 release, but otherwise there shouldn't have been any recent changes.

Can you try disabling all extensions, `code --disable-extensions` and see if the issue still reproduces?

**Comment by lxnow321** [comment]
> Hi @lxnow321 Where are you expecting View: Show Explorer that you don't see the command? I can see the command in the Command Palette:
> 
> ![image](https://user-images.githubusercontent.com/12818376/98588555-b7d0ba00-2280-11eb-906c-1da2adde73ca.png)
> 
> The "Auto Reveal" settings also are available in the Settings editor:
> 
> ![image](https://user-images.githubusercontent.com/12818376/98588994-712f8f80-2281-11eb-9a14-ed606d5e784a.png)
> 
> There was a new value added for Explorer: Auto Reveal, `focusNoScroll`, with the 1.46 release, but otherwise there shouldn't have been any recent changes.
> 
> Can you try disabling all extensions, `code --disable-extensions` and see if the issue still reproduces?

**Comment by lxnow321** [comment]
Thank you for your reply.  I try again，it is same invalid in my old workspace。I can see the command and use it，but it is in invalid. The editor can not focus opened file in  explorer when I use this command or use hotkey "ctrl+shift+e".
Buy when create new workspace ,it is valid.Maybe is my old workspace setting mistake.Thanks again.
