### ISSUE TITLE
Delaying in Push Source to Default Org while using Teams Meeting!

### ISSUE THREAD

**Issue by ubaymahfouz** [microsoft/vscode-docs#4247]
I am having an issue with VS code while using Teams Meeting, all the time either it delays or fails to Push source to default org, are you facing the same issue and what could be the reason?

once I disconnect the meeting it goes well!

**Comment by gregvanl** [comment]
Hi @ubaymahfouz I have not heard about the issue you describe. I wonder if this could be caused by limited bandwidth when you are connected to a Teams meeting. Does this happen if you turn off video to reduce the bandwidth required for Teams?
This repo is for VS Code documentation and issues with code.visualstudio.com topics.
You might be able to find an answer on StackOverflow https://stackoverflow.com/questions/tagged/visual-studio-code or try the VS Code product repo https://github.com/microsoft/vscode/issues
