### ISSUE TITLE
Default behavior for missing "redirectOutput" described incorrectly

### ISSUE THREAD

**Issue by bersbersbers** [microsoft/vscode-docs#4252]
See https://code.visualstudio.com/docs/python/debugging#_redirectoutput

> **When omitted** or set to true (the default for internalConsole), **causes the debugger to print all output from the program into the VS Code debug output window**. 

This statement alone would mean the following debug configuration should redirect output, but it doesn't:

```
            {
                "name": "Python: Test",
                "type": "python",
                "request": "launch",
                "program": "${file}",
                "console": "integratedTerminal",
                "internalConsoleOptions": "openOnSessionStart",
            },

```

It also contradicts the following statement:

> If set to **false (the default for integratedTerminal and externalTerminal**), program output is not displayed in the debugger output window.

I think "When omitted or" should be removed from the above. The behavior when omitted is described sufficiently and correctly by the defaults depending on `"console"`.

**Comment by JoshuaPartlow** [comment]
@int19h or @karthiknadig - Are you able to take a look and comment on the above feedback?

**Comment by karthiknadig** [comment]
Here is the default behavior. When omitted the default behavior depends on what the "console" setting options are.
1. `internalConsole`: Default is `"redirectOutput": true`. 
2. `integratedTerminal`: Default is `"redirectOutput": false`.
3. `externalTerminal`: Default is `"redirectOutput": false`.

The default for `internalConsole` is true because the process is not visible. @int19h Can correct me if I am wrong about the reason behind this.

As @bersbersbers suggested we should probably remove "When omitted or".

**Comment by int19h** [comment]
Yep, that's how it works. 

The reason why it's false for terminals is because the output is already captured there, and because redirecting stdout/stderr can affect behavior - e.g. on Unix-like systems, it means that the process is not attached to a tty. So the default is false to minimize the differences with running the debuggee directly. For "internalConsole", it defaults to true simply because otherwise there'd be no output at all.

**Comment by JoshuaPartlow** [comment]
Addressed in above PR.
