### ISSUE TITLE
"Debug: Select and Start Debugging" missing from the Command Palette

### ISSUE THREAD

**Issue by BretStateham** [microsoft/vscode-docs#4372]
The "[Debugging](https://github.com/microsoft/vscode-docs/blob/main/docs/editor/debugging.md)" document (line 124)
 indicates that a specific debug configuration can be selected and run via the keyboard by opening the Command Palette (Ctrl+Shift+P), and typing "Debug:  Select and Start Debugging" or by typing `debug ` and selecting the desired configuration.  

Neither option is working for me.  

I have a project with valid debug configurations that I can select and run using the mouse and or pressing F5, etc. But I can't easily change the debug configuration that is current selected using the keyboard.  This is an accessibility issue. 

![image](https://user-images.githubusercontent.com/1424362/110041799-f42d9780-7d01-11eb-9cfa-1c9b9ea558c6.png)

Is there another way that debug configurations can be selected via the keyboard in a reliable way (not just tabbing around and hoping we landed on the right control)?  It would be even better if we could assign keyboard shortcuts to specific debug configurations.

**Comment by gregvanl** [comment]
Hi @BretStateham Are you still having this issue? I am unable to reproduce it and I get a drop down with various debug configurations. I'm testing on the Yeoman generated VS Code extension project.

![image](https://user-images.githubusercontent.com/12818376/113089479-93786a00-919c-11eb-8887-678c7ec485e6.png)

![image](https://user-images.githubusercontent.com/12818376/113089514-a68b3a00-919c-11eb-8574-076be1dd8a4f.png)

If this issue is still blocking you, it might be better to open an issue in the VS Code product repro at https://github.com/microsoft/vscode as this repo is for VS Code documentation issues.

I don't think you can assign keyboard shortcuts to specific debug configurations but you could enter a suggestion issue.

**Comment by gregvanl** [comment]
No response from user so closing
