### ISSUE TITLE
Document known browser limitations

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-docs#4373]
Document limitations in areas such as keybindings, extensions.

Live Share extension example: https://docs.microsoft.com/en-us/visualstudio/liveshare/reference/extensions#user-specific-extensions.

**Comment by lramos15** [comment]
As @bamurtaugh requested just adding my Flutter findings here.

- Flutter recommends installation from snap, but snap cannot be installed within the codespaces docker container and they currently don't plan to support it
- Installing Flutter manually seems to work, but common workflows such as Android Emulation do not work within a docker container
- From my understanding codespaces cannot detect USB devices plugged into your machine, which also makes development on a physical device impossible
- Codespaces, like other linux environments, doesn't support iOS development.

This limits the Flutter experience that **might work** to physical android devices only. For that reason and the complex manual setup required for it, Flutter isn't really a supported experience in codespaces and I feel it isn't expected to be.

**Comment by gregvanl** [comment]
Document is still a work in progress so moving to May milestone

**Comment by sbatten** [comment]
For LaTeX workshop extension:
The extension provides 3 surface areas of features to help with LaTeX authoring. The first is a set of views which surface common commands. The views themselves work without issue but a few of the commands try to launch native applications like revealing the output folder in the OS file explorer. These do nothing in codespaces web.

The second is a PDF previewer. "latex-workshop.view.pdf.viewer" => This setting provides a PDF previewer similar to the markdown preview. You can preview in a browser tab, in a separate pdf viewer, or in a VS Code tab. Only the browser tab is usable in Web Codespaces. The separate PDF viewer fails silently and the VS Code tab hits the Content Security Policy issue. The VS Code Tab viewer has other nice features that aren't available due to this limitation.

Lastly, it provides snippets, intellisense, and other general language features that seem to work without issues. So, in summary, the extension can be used fairly full featured, but some things just don't work right now and need to be worked around.

**Comment by gregvanl** [comment]
Published at https://code.visualstudio.com/docs/remote/codespaces#_known-limitations-and-adaptations
