### ISSUE TITLE
Unable to write file 'c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\.vscode\tasks.json' (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, mkdir 'c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\.vscode')

### ISSUE THREAD

**Issue by OJSIY202310** [microsoft/vscode-docs#4388]

**Comment by gregvanl** [comment]
Hi @OJSIY202310 Looks like you don't have permissions to write to the Visual Studio IDE install location. I'm not sure what your scenario is but you probably want to avoid modifying the VS IDE install folders and instead do you work under your user folder.
To get started using VS Code, you may find our starting tutorials helpful, for example https://code.visualstudio.com/docs/nodejs/nodejs-tutorial, starts with a simple Hello World Node.js application.
Closing this issue since it doesn't look like a documentation problem.
