### ISSUE TITLE
Terminal error

### ISSUE THREAD

**Issue by Yashdhoot** [microsoft/vscode-docs#4505]
![16196799514216767646811067680100](https://user-images.githubusercontent.com/83392693/116513605-7ba11c80-a8e7-11eb-8269-3b6725f43c0e.jpg)

Can anyone help me with this... Iam new at this
It is c++

**Comment by gregvanl** [comment]
Hi @Yashdhoot I'm sorry you are having trouble with your C++ program.
This repo is for VS Code documentation issues and you may have better luck solving your issue by posting your question on a site like Stack Overflow.
I did a search on SO and found an entry that might help with your issue https://stackoverflow.com/questions/5259714/undefined-reference-to-winmain16.
I'm closing this issue because I don't think it is related the VS Code documentation.
