### ISSUE TITLE
Introduce a common architectural diagram language (and use it where needed)

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-docs#453]
The VS Code doc lacks architectural diagrams that help the reader to orientate himself in the overall architecture. Something along the lines of this:

![2016-07-05_12-17-51](https://cloud.githubusercontent.com/assets/1898161/16581595/9d0a1352-42aa-11e6-96b7-a90a2ce7a606.png)

Architectural diagrams should be used in the 'Overview', 'Example Language Server' and 'Examples Debuggers' chapters of 'Extensions'.

/cc @egamma

**Comment by dbaeumer** [comment]
And one from me :-)

![capture](https://cloud.githubusercontent.com/assets/1931590/17627603/124a0378-60b2-11e6-9746-870ed8a9896e.png)

**Comment by octref** [comment]
Just chiming in these graphs would have helped me tremendously, if they were available when I started contributing to Code.

I also remember @Tyriar saying we can improve community contribution. I saw in a lot of issues some people were trying to contribute but gave up, possibly because they don't know where to start. This would definitely help.
