### ISSUE TITLE
Clang + LLDB on Windows 7

### ISSUE THREAD

**Issue by zeronnath** [microsoft/vscode-docs#4575]
Hello,
I see the official MS documents for CLANG + LLDB is only for MacOS 
https://code.visualstudio.com/docs/cpp/config-clang-mac

MS provides docs only for MacOS, is it becuase it doesn't work on Windows?

I tried the above on windows 7. It didn't work.
yes, I used the directory for windows.
yes,  ".exe" file.
etc.

I got the following output.
& 'c:\Users\Thuban\.vscode\extensions\ms-vscode.cpptools-1.4.0\debugAdapters\bin\WindowsDebugLauncher.exe' '--stdin=Microsoft-MIEngine-In-3q5w4pgu.3se' '--stdout=Microsoft-MIEngine-Out-gfhfvdmr.gow' '--stderr=Microsoft-MIEngine-Error-njr1glfc.zwf' '--pid=Microsoft-MIEngine-Pid-51dcillx.3jl' '--dbgExe=D:\program files (x86)\LLVM\bin\lldb.exe' '--interpreter=mi'

I see also the default is LLDB-MI.exe, which I don't have in my LLVM bin.
(I used llvm v11.)

**Comment by tiziodcaio** [comment]
If it would be possible, add the guide generally for all windows version (I tried too without successing)...

**Comment by jureid** [comment]
Hi @zeronnath and @tiziodcaio, 

The C++ extension debugger is dependent on lldb-mi, which has been removed from recent versions of LLVM (LLVM 9.0 was the last release that included lldb-mi). We're investigating a way to ship it on our own so that we can enable debugging with LLVM 10+.

This isn't an issue for macOS users because we can link to XCode's version of liblldb.framework. **For Windows and Linux users, we recommend using the [CodeLLDB](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb) extension to debug with LLDB in VS Code.**

**Comment by jureid** [comment]
I'm going to close this issue as a workaround has been provided and we haven't heard back from the customer.

**Comment by tiziodcaio** [comment]
I'm not so expert, and I tried without success, so I didn't answered....
