### ISSUE TITLE
Not autodetecting new Python venv (Windows; first venv was outside Code; WSL and Ruby extensions also installed) 

### ISSUE THREAD

**Issue by reed9999** [microsoft/vscode-docs#4592]
The article [Using Python environments in VS Code](https://code.visualstudio.com/docs/python/environments#_global-virtual-and-conda-environments) asks us to file an issue if a new environment isn't autodetected. I also can't get my code run in the Code debugger to see libraries installed in my new environment.

For the most part this is a brand new installation of Code so I'm not sure what's useful to troubleshoot.
```
OS Name	Microsoft Windows 10 Home
Version	10.0.19042 Build 19042
...
System Manufacturer	HP
System Model	HP Pavilion Laptop 15-eg0xxx
System Type	x64-based PC
...
Processor	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz, 2419 Mhz, 4 Core(s), 8 Logical Processor(s)
```

```
VS Code version: 1.56.2
Commit 05489...
```

Before adding Python extensions, I added Remote-WSL, Ruby, and VSCode Ruby, but haven't used them. I've subsequently loaded: 

```
Jupyter  v2021.6.832593372 (not using yet)
Pylance v2021.6.0
Python v2021.5.842923320
```

Going by memory, so far I have: 
- Used `venv` to create a VE in a new `.venv` dir under my home dir.
- At some point I think I used `virtualenv`
- Based on the above-linked doc, I've tried 2-3 times to create new VEs in the PowerShell Terminal that came with VS Code out of the box, from the project's root dir:

```
python -m venv .venv     
.\.venv\Scripts\activate.bat
 python -c "import requests"
```
At no point has a dialog box such as the one depicted in the article popped up for me. 

## Secondary issue (not the one you asked readers to file)

In the last code snippet, the import works fine in PowerShell within Code. But trying to debug a Python script in Code (F5) with `import requests` near the top fails with:
```
Exception has occurred: ModuleNotFoundError
No module named 'requests'
  File "C:\Users\phili\code\slowgames\legacy\site_yucata\classify_games.py", line 11, in <module>
    import requests
```
(Explicit repathing via sys.path fixes the above issue.)

Also fwiw I would have installed requests in the global environment somewhere in there, but uninstalled it before the last creation of a venv. I've also restarted Code several times in there.

**Comment by JoshuaPartlow** [comment]
Hi @reed9999 - Thanks for opening an issue. I think this might be better suited to the extension repo though. If you could fill out the below issue template, I can transfer the issue over to the other repo for you or you [could open it there](https://github.com/microsoft/vscode-python/issues) yourself if you'd prefer.


## Environment data

-   VS Code version: XXX
-   Extension version (available under the Extensions sidebar): XXX
-   OS and version: XXX
-   Python version (& distribution if applicable, e.g. Anaconda): XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: XXX

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX



## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by JoshuaPartlow** [comment]
Closing given time open. If this is still a problem, please open an issue on the [extension repo](https://github.com/microsoft/vscode-python/issues).
