### ISSUE TITLE
Unable to use "code ." command in terminal

### ISSUE THREAD

**Issue by aidanmcgrath** [microsoft/vscode-docs#4797]
After following the instructions perfectly in the "Using GCC with MinGW" article, the "code ." command is not recognized in my mingw terminal. I downloaded vscode and all of the required extensions, downloaded the recommended MSYS2 Mingw-w64 version, and followed the instructions on updating the windows path environment variables exactly as listed in the article. The g++ and gdb tools work as intended in my terminal, but after going into a new directory, the terminal says the "code ." command is not found. I have tried uninstalling both vs code and MSYS2, nothing seems to be working. Any help would be greatly appreciated.

**Comment by gregvanl** [comment]
Hi @aidanmcgrath 
Are you able to run VS Code from the Start menu? 
Also does `code .` work if you try from a Command Prompt?
I am assuming you are on Windows since you are working through the "Using GCC with MinGW" tutorial.

**Comment by SkylerMime** [comment]
I'm having a similar issue on my Macbook using macOS Big Sur.

I followed the instructions in this article:
https://code.visualstudio.com/docs/cpp/config-clang-mac

I already had clang installed because clang --version works. I've installed xcode, Visual Studio Code, and the C++ extension for vscode.

I tried following these instructions: ![image](https://user-images.githubusercontent.com/89657777/132058907-6f0dba1c-3c2d-4601-aff0-0e3903af372c.png)

But when I tried the last command, **code .**, I got the error **-bash: code: command not found**

Any idea how I can fix this? I suspect it might have something to do with the fact that I'm using bash instead of zsh, but maybe that doesn't matter.

![image](https://user-images.githubusercontent.com/89657777/132059123-38d2a829-7465-40ea-8666-fc8dcfccf3ae.png)

Thanks for your help!

**Comment by gregvanl** [comment]
Hi @SkylerMime On macOS, you need to explicitly add VS Code to your path via the ** Shell Command: Install 'code' command in PATH** command.
https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line
Unlike Windows and Linux, the VS Code binary location isn't added during installation.

**Comment by SkylerMime** [comment]
That fixed the issue, thank you so much!

**Comment by gregvanl** [comment]
Closing as no reply from original issue author.
