### ISSUE TITLE
Cannot run build:  fatal error LNK1107: invalid or corrupt file: cannot read at 0x1D6

### ISSUE THREAD

**Issue by HaoSun1** [microsoft/vscode-docs#4843]
Following the instructions here: https://code.visualstudio.com/docs/cpp/config-msvc

When I get to run the build task  I get the following output

```
Starting build...
cl.exe /Zi /EHsc /nologo /Fe: "C:\Users\user\Google Drive\CFolder\projects\helloworld\.vscode\tasks.exe" "C:\Users\user\Google Drive\CFolder\projects\helloworld\.vscode\tasks.json"
cl : Command line warning D9024 : unrecognized source file type 'C:\Users\user\Google Drive\CFolder\projects\helloworld\.vscode\tasks.json', object file assumed

C:\Users\user\Google Drive\CFolder\projects\helloworld\.vscode\tasks.json : fatal error LNK1107: invalid or corrupt file: cannot read at 0x1D6

Build finished with error(s).
The terminal process terminated with exit code: -1.
```

How do I fix this?

**Comment by gregvanl** [comment]
Hi @HaoSun1 Make sure the active file is helloworld.cpp. You'll see this error if you still have editor focus on the tasks.json.
The build configuration always tries to build the active file, since "args" uses the `${file}` placeholder.

The instructions call out going back to helloworld.cpp:

![image](https://user-images.githubusercontent.com/12818376/134399912-25c84890-495d-41ab-89c1-6b0a42d853b7.png)

**Comment by gregvanl** [comment]
Closing as haven't heard back. I assume you are unblocked.
