### ISSUE TITLE
max image size referenced by readme

### ISSUE THREAD

**Issue by bengreenier** [Microsoft/vscode-docs#487]
> TL;DR; Is there a filesize limit on images referenced by README.md when served via the marketplace?

When viewing my extension in the marketplace [here](https://marketplace.visualstudio.com/items?itemName=bengreenier.vscode-node-readme) i don't see my `example.gif` being rendered. Is there a filesize limit imposed? I closely mirrored https://github.com/Microsoft/vscode-spell-check when creating my extension https://github.com/bengreenier/vscode-node-readme and the only difference i see is with filesize.

**Comment by gregvanl** [comment]
README images are not actually uploaded to the Marketplace, instead the image path is converted to a URL pointing to the extension repository.  Since you haven't specified a repository in your extension's package.json, this path conversion is failing and the image element src is an empty string.
Try setting the repository field in your package.json.

**Comment by bengreenier** [comment]
gotcha, thanks @gregvanl - is this documented anywhere? If not i'd be happy to add it...might be good to have as a note somewhere, at least.

**Comment by gregvanl** [comment]
The repository field is mentioned about but incorrectly called out as an optional field. I'll update the docs and enter a bug for the vsce tool to issue a warning if the repository field isn't set.

**Comment by gregvanl** [comment]
The extension page on the Marketplace now has the image after republishing with the repository field set in the extension's package.json.
