### ISSUE TITLE
paragraph change in Documentation Issues

### ISSUE THREAD

**Issue by raghavthind2005** [microsoft/vscode-docs#4940]
In **"Document  Issues"**, there are two paragraphs consisting of one sentence each.
These sentences could be combined to form a single paragraph for better syntax.
 
![InkedScreenshot 2021-11-05 17 26 04_LI](https://user-images.githubusercontent.com/84238519/140507092-b9a5034e-9f4c-4a1a-a838-17186cd5600d.jpg)

**Comment by gregvanl** [comment]
Hi @raghavthind2005 Thank you taking the time to open an issue and your interest in the VS Code documentation.
The two sentences cover two different scenarios; doc issues versus product issues, so we'd like to keep the scenarios in two different paragraphs. 
We also want to make it as easy as possible for readers to parse the two scenarios since it makes issue triage easier if bugs go to the correct repo.

**Comment by raghavthind2005** [comment]
Hello @gregvanl !
Thank you for the clarification.
