### ISSUE TITLE
Data breakpoints: how to create them and which debugger supports it

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode-docs#5236]
On the [Debugger](https://code.visualstudio.com/docs/editor/debugging) page there is mention of [Data breakpoints](https://code.visualstudio.com/docs/editor/debugging#_data-breakpoints).

Where in the `VARIABLES` view is the UI to create a Data breakpoint?

Which debuggers support Data breakpoints?

I tried with Python and JavaScript but did not succeed.

**Comment by roblourens** [comment]
Those debuggers don't support data breakpoints- to my knowledge, only Java has implemented this support

**Comment by yuis-ice** [comment]
I'm also the one who encountered to the OP's question on the document mention. I see you're closing the issue but since the issue is labelled as a doc-bug, isn't the document should have a correction? I'm not sure I'm new to vscode-docs. Tell me if it's wrong. 

You say they don't support, but only Java. Since it's not "for now" or "in near future it could have" or "Java and blah blah", I think it's worth noting explicitly "Java" on the document.

**Comment by roblourens** [comment]
The doc says "If a debugger supports data breakpoints..." that is accurate. I don't want to keep a list of which debug adapters support which features, if I did I'm sure it would be quickly out of date.

**Comment by rioj7** [comment]
@roblourens I don't request a list of supported debuggers, I want a description/image of what is visible in the Variables view when  the debugger supports Data Breakpoints. A small explanation on how to set them. It now only mentions that it can be done, not how it can be done.

**Comment by roblourens** [comment]
I can add a little extra detail on how to set them, when possible.
