### ISSUE TITLE
Document `editor.codeActionsOnSave`

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-docs#5276]
The docs only seem to reference it in the [default settings](https://code.visualstudio.com/docs/getstarted/settings#_default-settings). Otherwise I always have to refer to https://code.visualstudio.com/updates/v1_57#_sort-imports-source-action on how to use it (and I don't know all the possible values it could contain).

**Comment by codewithdev** [comment]
@brettcannon I believe `editor.codeActionsOnSave` has multiple settings.

From https://github.com/microsoft/vscode-docs/blob/ad85eb71a0d989be6d288d2d36ce2fb131db0ad9/release-notes/v1_23.md#run-code-actions-on-save 

There might be different settings and it can be documented for sure.

**Comment by jeremy-allocate** [comment]
+1 for better documentation around this.  The format has changed since this ticket was opened, and it no longer accepts boolean values and can be either and array or an object: https://github.com/microsoft/vscode/issues/194861

Vscode release notes are currently the best place to find info on this option.

**Comment by ntrogh** [comment]
It took a while, but it's coming!

**Comment by jeremy-allocate** [comment]
Thanks @ntrogh!
