### ISSUE TITLE
Compare Visual Studio Code and Visual Studio

### ISSUE THREAD

**Issue by vedant205** [microsoft/vscode-docs#5284]
I think a page on the vscode docs that compares the features/use cases of visual studio code and visual studio would be helpful for users to be able to decide which one to download and to clear up any confusion.

**Comment by gregvanl** [comment]
Hi @vedant205 We mention the difference briefly in https://code.visualstudio.com/docs/supporting/faq#_what-is-the-difference-between-visual-studio-code-and-visual-studio-ide.
We avoid a side-by-side comparison since it really depends on which VS IDE workloads and which VS Code extensions you have installed. VS IDE can be used as a simple editor, like VS Code, or conversely, VS Code can almost be an IDE, if you have many powerful extensions installed (debuggers, profilers, formatters).
The download for VS Code is very quick so hopefully users can try it out and see if it meets their needs or if they need something with more features out-of-the-box like VS IDE.

**Comment by vedant205** [comment]
Thank you for the explanation!
