### ISSUE TITLE
404 for "Debugging" link in Python Interactive window docs

### ISSUE THREAD

**Issue by tomvothecoder** [microsoft/vscode-docs#5333]
Page: https://code.visualstudio.com/docs/python/jupyter-support-py

Broken Link: https://code.visualstudio.com/docs/python/debugging.md

Screenshot
![image](https://user-images.githubusercontent.com/25624127/167953681-5db4493c-d1da-4eb9-abd6-2e0821d31945.png)

**Comment by gregvanl** [comment]
Hi @tomvothecoder Thanks for pointing this out!
I think the link is meant to go the general VS Code debugging topic rather than the "Python debugging in VS Code" since that section is talking about general debugging flow and UI and not about specific Python debugging configuration.
I wanted to fix the 404 quickly but @rjmolyneaux can follow up and confirm this is the intention.

**Comment by tomvothecoder** [comment]
No problem @gregvanl! Thanks for getting to it so fast.
