### ISSUE TITLE
Cannot find an link to information about workspaces in docs

### ISSUE THREAD

**Issue by valankar** [microsoft/vscode-docs#5435]
Searching Google I found:

https://code.visualstudio.com/docs/editor/workspaces

However it seems there is no link to this page from anywhere else in the docs at:

https://code.visualstudio.com/docs

Is it perhaps already linked somewhere?

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by gregvanl** [comment]
Hi @valankar You are correct that we don't include the Workspace topic in the table of contents and this is by design. Our thinking is that new users shouldn't need to understand the "workspace" concept as defined by VS Code to begin working with VS Code and we don't want people getting initially bogged down.
We have links from various places in the documentation to direct people to the Workspace topic, if they want to learn more.
For example:
In the FAQ: https://code.visualstudio.com/docs/supporting/faq#_what-is-a-vs-code-workspace
In Settings: https://code.visualstudio.com/docs/getstarted/settings#_workspace-settings
In Workspace Trust: https://code.visualstudio.com/docs/editor/workspace-trust

We try to downplay the concept, with explanations such as:

![image](https://user-images.githubusercontent.com/12818376/176699555-7f137764-397c-40e7-b6f0-e43277c8c27b.png)
