### ISSUE TITLE
Question: ReadMe Table of Contents

### ISSUE THREAD

**Issue by krupalitrivedi** [microsoft/vscode-docs#5659]
Greetings! 

As GitHub has added a table of contents already as an integration, what is the specific need to add the Table of Contents again in the ReadMe. When the table of contents is already generated, I do not feel like it should be embedded again but I would like to know moreif there are any specific reasons! 

Thank you!

**Comment by gregvanl** [comment]
Hi @krupalitrivedi, I'm not sure I understand your question. Are you speaking about the "Index" at the top of the README? Does GitHub have an optional TOC view that people can enable?
We have the index at the top of the README so that people can quickly find the section they need, for example how to contribute.

**Comment by gregvanl** [comment]
I think I see the TOC you mention. There is the dropdown in the upper right on GitHub.

![image](https://user-images.githubusercontent.com/12818376/193370709-6d3ce6cc-10d4-43bf-a779-a10d41a59988.png)

We'd like to leave the index so people can find the section quickly without the dropdown and also some people may be reading the README on a local clone of the repository. 

For example, reviewing the README with VS Code's Markdown Preview (Ctrl+Shift+V) conveniently displays the links at the top of the page.

![image](https://user-images.githubusercontent.com/12818376/193371430-e8cfd2b3-72cc-4736-834e-94e6b89c8b7b.png)
