### ISSUE TITLE
Migrate Codespaces content from VS Code docs to GitHub docs

### ISSUE THREAD

**Issue by craiglpeters** [microsoft/vscode-docs#5685]
As we improve the GitHub documentation for Codespaces, it seems we should consider migrating some content that currently exists only in the VS Code docs to the GitHub docs for Codespaces. I've created this issue to discuss the matter.

@bamurtaugh made the following observation
> https://code.visualstudio.com/docs/remote/codespaces points to some specific extension info (https://code.visualstudio.com/docs/remote/codespaces#_extension-authors) and limitations (https://code.visualstudio.com/docs/remote/codespaces#_known-limitations-and-adaptations, https://code.visualstudio.com/docs/remote/codespaces#_common-questions) that I think may not be in GH docs.

**Comment by bamurtaugh** [comment]
Thanks for opening this issue. To me, there are a couple of options here:

- Keep this Codespaces page on the VS Code docs site, and be sure to update with the latest Codespaces info and perhaps even more often or clearly point to GH docs
- Update GH docs to include info on or links to the content I mentioned above, and then consider if we'd like the Codespaces node just to redirect to Codespaces docs

**Comment by gregvanl** [comment]
Closing this old tracking issue. Feel free to reopen if anyone wants to revisit refactoring these docs.
In general, the VS Code Codespaces topic is designed for discovery, to present the value proposition of GitHub Codespaces, and to provide necessary information for VS Code extension authors so that their extensions perform well in both VS Code Desktop but also remote environments like Codespaces.
