### ISSUE TITLE
IntelliSense images are big

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#575]
From @seanmcbreen 

> In the intellisense doc the images are pretty big

**Comment by waderyan** [comment]
@seanmcbreen can you describe what you are seeing? Is this a bug or is this feedback on the images are larger than you expect?

**Comment by Tyriar** [comment]
The images seem to be stretched version of the icons, eg. https://code.visualstudio.com/images/intellisense_method_icon.png

So they're a little blurry and they take up a huge amount of space (49x50px for one above). 32x32px at the most would probably look better.

**Comment by Tyriar** [comment]
If we were to keep them at this size they should be higher fidelity and vertically center the text imo. Also a 2 column table may be better as right now all the icons don't fit on my screen.

**Comment by seanmcbreen** [comment]
I agree with Daniel - they were stretched and just looked a little odd in the table.  Here is a screenshot.

<img width="263" alt="icons" src="https://cloud.githubusercontent.com/assets/1051190/18517863/adff0ed0-7a52-11e6-9e99-0d9d94d2ac23.png">

I would expect the icons in the table to be similar to the icons in the product - specifically the size vs the text size.

**Comment by waderyan** [comment]
Thank you for your feedback. Added to Sep.

**Comment by waderyan** [comment]
@bgashler1 not a high priority, but when you have a few minutes can you send me smaller versions of the above files?

**Comment by bgashler1** [comment]
@waderyan sure.

**Comment by gregvanl** [comment]
To my eye they look fine and it's nice to have them big enough to see and understand. Reopen if you think we should fix the images.

**Comment by Tyriar** [comment]
@gregvanl I disagree. Here is the current situation:

![image](https://cloud.githubusercontent.com/assets/2193314/21575617/4975b5f8-cec7-11e6-9e94-e055df0285b9.png)

I see the following problems:

- The images take up pretty much the entire height of a maximized window on a 1080p monitor.
- The images also appear to be screenshots of the source images and then stretched, not even stretched at an even percentage so they are extra blurry. The source images are svgs so we should be using them regardless of the size chosen so the images are not blurry.
- Since we're not using SVGs these will also look particularly bad on retina displays where the screen density is x2
- The method image appears to be out of date.
- The images have more whitespace on the bottom than the top: 
  ![image](https://cloud.githubusercontent.com/assets/2193314/21575664/0c4945da-cec9-11e6-970a-d9dd0bed53cd.png)
- The text is aligned to top, this might look better being aligned to the middle like the images are

Here are comparisons of the current image to a the scaled SVG that is used in product:

Current:

![image](https://cloud.githubusercontent.com/assets/2193314/21575645/966a9d3c-cec8-11e6-8d86-96f45e143434.png)

![image](https://cloud.githubusercontent.com/assets/2193314/21575647/9fa635aa-cec8-11e6-8cc6-19155a606a9c.png)


Method_16x.svg scaled to 32x32:

![image](https://cloud.githubusercontent.com/assets/2193314/21575643/6dff348e-cec8-11e6-83a1-6f0a07c3bdc4.png)

![image](https://cloud.githubusercontent.com/assets/2193314/21575644/8e7d5cae-cec8-11e6-8e3e-0352d8cd22f4.png)

Notice the crispness of the image when the svg is scaled directly.

Now compare the [current look](https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions) (takes up ~850px vertically):

![image](https://cloud.githubusercontent.com/assets/2193314/21575700/8540aad6-ceca-11e6-9ebf-eb44fb11ab10.png)

To the alternatives:

Single item, less padding, scaled svg, centered text (would take up 507px vertically):

![image](https://cloud.githubusercontent.com/assets/2193314/21575713/c61a43d2-ceca-11e6-92b3-807c027b4bba.png)

Same as above but 2 columns via a media query if there is enough space (would take up 273px vertically):

![image](https://cloud.githubusercontent.com/assets/2193314/21575728/2eab7d44-cecb-11e6-81aa-b0bab386ba77.png)

**Comment by Tyriar** [comment]
Looking into this a little more, the table itself seems quite out of date.

**Comment by Tyriar** [comment]
I created a PR to use the SVGs and update the descriptions https://github.com/Microsoft/vscode-docs/issues/790

**Comment by Tyriar** [comment]
Looks good after https://github.com/Microsoft/vscode-docs/pull/790 so closing this off, the images are smaller as well so the height/alignment issue isn't as big.

![image](https://cloud.githubusercontent.com/assets/2193314/21696544/671bface-d343-11e6-9f13-71f2b9e7abc9.png)
