### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by sumitshinde-84** [microsoft/vscode-docs#6095]
hellow i want to fix an issue in header of vscode website 
but i facing problem while finding file where i can make changes can anyone help me?

**Comment by gregvanl** [comment]
Hi @sumitshinde-84 The website infrastructure is in a private repo and this public vscode-docs repo contains just the topic Markdown files.
What issue are you seeing with the VS Code website and what is your proposed fix?

**Comment by sumitshinde-84** [comment]
![Screenshot (77)](https://user-images.githubusercontent.com/110285294/221915588-c8bab87e-2d5b-4f88-a363-44d60d89044c.png)

![Screenshot (76)](https://user-images.githubusercontent.com/110285294/221915660-908adb43-3cc8-4d4a-9ab1-42906e10bb64.png)

**Comment by sumitshinde-84** [comment]
expected according to me 

![Screenshot (68)](https://user-images.githubusercontent.com/110285294/221916015-e8bd5ad1-a00c-4de3-9b33-5c513b599f80.png)

![Screenshot (65)](https://user-images.githubusercontent.com/110285294/221916057-4bf67a18-fb67-41df-9a1c-c3e47091b729.png)

**Comment by gregvanl** [comment]
Thanks for providing details. You are not alone in wanting to modify the button styling! Here's an early mock up of the changes being considered for a website refresh.

![image](https://user-images.githubusercontent.com/12818376/221918675-690db87a-5b43-4481-8a84-3f53d3dd5cf0.png)

I'm going to close this issue since website changes are handled by the internal engineering and UX teams but I'll be sure to reference your suggestion.

**Comment by sumitshinde-84** [comment]
Thank you  so much sir
