### ISSUE TITLE
Review and update Terminal Basics

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-docs#6108]
CSAT remains low at 37% in Dec/Jan while popular ranked #24 in page views 
Specifically look at Git Bash set up in the Terminal (common verbatim comment)

**Comment by Tyriar** [comment]
It looks like the problem might be caused by git being installed in a non-default directory: https://stackoverflow.com/q/42606837/1156119

Even if we did detect this case, they would be unsafe paths that we cannot expose in the dropdown by default https://code.visualstudio.com/docs/terminal/profiles#_unsafe-profile-detection

**Comment by Tyriar** [comment]
Perhaps we should be checking the path for git.exe and finding bash.exe from that? Similar to the git ext:

https://github.com/microsoft/vscode/blob/a6c67db75057d81d0ebc8f7d0d926a48264b3997/extensions/git/src/git.ts#L132-L135

**Comment by Tyriar** [comment]
Improved detection in https://github.com/microsoft/vscode/pull/176063

**Comment by gregvanl** [comment]
Address a couple of doc feedback comments with https://github.com/microsoft/vscode-docs/pull/6192

Expect that 1.77 release with better git.exe detection should help CSAT. For example, 3/7 frowns in March were about setting up Git Bash
