### ISSUE TITLE
DOC:  Link from release notes to relevant PR

### ISSUE THREAD

**Issue by corneliusroemer** [microsoft/vscode-docs#6119]
I like reading the release notes. But they are quite brief. I often don't know exactly what is meant. So I would like to have a look at the relevant PRs and or issues or however the feature was tracked before it ended up in the code base.

Unfortunately, I couldn't find a good way to do this. There only seems to be the release notes on the website, but no changelog in the repo itself - or am I missing something?

It would be great if there was better information linking. I get that you may not want to pollute the release notes with PR links, but maybe there's another way.

My particular use case is that I opened an issue a week or two ago, and wondered whether something in the release notes could fix/affect it.

**Comment by corneliusroemer** [comment]
Some further thoughts: I realized that you _do_ include some fixed issues and PR contributions in the release notes.

However, compared to the very well edited general release notes that are pitch perfect, this appendix (despite shown to everyone who scrolls this far) that section does not seem to get enough attention. They seem almost entirely automated. There are items like: `Bump distro [PR #175115](https://github.com/microsoft/vscode/pull/175115)` that don't serve any discernible benefit.

If the purpose is to thank people then there are probably better ways than include random PR links with random descriptions without context.

It feels like you include too little detail on the big highlights (no link to PR etc.) and too much detail on outside contributions (PR title, link, when the name should be enough) - anyone can quickly query the repo anyways to find out which PRs that person contributed too.

<img width="1724" alt="image" src="https://user-images.githubusercontent.com/25161793/223526679-3e740c92-67bd-4220-a1b8-d664e21a9dfc.png">

**Comment by gregvanl** [comment]
Hi @corneliusroemer I'm glad you like the VS Code release notes and appreciate your feedback and interest in the VS Code documentation.
As you correctly guessed, the "Thank you Pull requests" section is automatically generated for the various VS Code repos and while we try to remove entries of low value (such as dependabot PRs), we sometimes miss an item (like "Bump distro"). The goal of the Thank you section is to express our appreciation to the community for contributing and, while you can follow PR links to issues and discussions, it isn't really meant to describe the full set of changes in the release.
We try to strike a balance with the release notes and call out the new features and fixes in a lightweight developer to developer style (VS Code engineers write up the section on their contributions for the milestone) while not making them too long or detailed. Sometimes deeper engineering discussions around features become blog posts (such as https://code.visualstudio.com/blogs/2022/08/16/markdown-language-server and https://code.visualstudio.com/blogs/2022/11/28/vscode-sandbox).
I'm not sure how well we could map new features to specific PRs since a feature may be months in the development; first as a prototype in a private branch, then as a preview enabled by a setting or on the Insiders build, until finally released for stable. A feature could have tens, even hundreds of commits and PRs.
Given that VS Code is open source on https://github.com/microsoft/vscode, you may be able to find details about a feature or fix by searching the repo (for example, by searching for a string in the feature's UI) to find the code, review it's GitHub history, and look for related issues and PRs.

**Comment by gregvanl** [comment]
Closing as no upvotes and no response from user.
