### ISSUE TITLE
No mention of adding VSCode's bin to MSYS2's $PATH

### ISSUE THREAD

**Issue by amkhrjee** [microsoft/vscode-docs#6212]
In the article [Using GCC with MINGW](https://code.visualstudio.com/docs/cpp/config-mingw), there is no mention of adding VSCode's bin directory to MSYS2's `PATH` as a troubleshooting method when `code` command does not work inside MSYS2. 

In my case, the bin directory was not added to MSYS2's `PATH` for whatever reason and I was not able to  open VSCode with the `code` command. It took me couple of minutes get to the root of the problem as there was no mention of this in the doc.

Doing a `PATH=/c/Users/{Username}/AppData/Local/Programs/'Microsoft VS Code'/bin:$PATH` solved the problem for me.

**Comment by gregvanl** [comment]
Hi @amkhrjee Thank you for your interest in the VS Code documentation and taking the time to create a issue.
The tutorial is written to enable VS Code to run from a Windows native environment rather than a MSYS2 environment. MSYS2 is only included as a way to install the MinGW toolset.
We'll leave it up to people who want to use the MSYS2 environment, rather than Windows Command Prompt, to learn how to set up the MSYS2 Path by reviewing the MSYS2 documentation.
