### ISSUE TITLE
Add new section about using TypeScript shipped with VS 2015

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode-docs#629]
There is some discussion in this [issue](https://github.com/Microsoft/vscode/issues/11745) about the difficulties of understanding what is going on when there is a version mismatch between workspace tsc and global tsc. 

We link to a this section in the docs, but it does not give information about the cause ... rather it gives information about how to upgrade the tsc version. We should add a section to the TypeScript docs that cherrypicks from [this release note section](http://code.visualstudio.com/updates#_languages) (per @dbaeumer [comment](https://github.com/Microsoft/vscode/issues/11745#issuecomment-251347995) we prefer not to link to the release notes but to the official doc).

**Comment by waderyan** [comment]
@gregvanl it would be great if you or I could pick this up soon...

**Comment by thomthom** [comment]
I'd like to suggest that the docs describe how to set VSC to use the shipped TypeScript - for users who get mismatch because they have VS2015 installed and don't want to install npm.

**Comment by gregvanl** [comment]
Added description of checks and settings to http://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions.
Leaving open and moving to November to look into Visual Studio 2015 scenario

**Comment by gregvanl** [comment]
@thomthom I looked into having VS Code use the VS 2015 or 2017 TypeScript install for the language service and it turns out to be problematic in several ways. The VS TypeScript install is custom VS and so the language service isn't compatible with VS Code (no tsserver.js to point to with VS Code settings tsserver.tsdk). Given it is a custom implementation different from the npm version, there is no guarantee of backward compatibility and so could break on a VS update.
Our recommendation is users either disable the warning message (setting  "typescript.check.tscVersion": false) or install the matching version of typescript with npm in their workspace (npm install typescript@version).
