### ISSUE TITLE
doc request what vscode files should be checked in to git

### ISSUE THREAD

**Issue by duaneellissd** [microsoft/vscode-docs#6368]
and a .gitignore file would be good

please also add/require that extensions (ie python and c/c++) document their files too.

**Comment by gregvanl** [comment]
Hi @duaneellissd Thank you for your interest in the VS Code documentation and providing this suggestion.

Because specific programming languages and projects have such different artifacts and assets, a general recommendation would be difficult and may not apply in most cases.

I would recommend talking with your team or collaborators as to which assets need to be shared via Git and which should remain local to an individual's local file system.

A rule of thumb would be to start by committing a minimum set of source code files, try setting up a new dev environment on a clean machine or VM, and determining what assets are missing.
