### ISSUE TITLE
Document the rules regarding placement of results in the VS Code Marketplace Search Results

### ISSUE THREAD

**Issue by krisfoster** [microsoft/vscode-docs#6397]
Hi - this might not be the right place for this, but I'm interested in finding out what the rules are governing the placement of extensions within the search results within the VS Code marketplace for extensions. Is this documented anywhere? And, if it isn't, could it be documented?

Thanks :)

**Comment by isidorn** [comment]
Thanks for opening this issue. But the Marketplace search results are dynamic, and the search algorithm is constantly changing. So it is not easy to document this. And it might be easier to document on the marketplace side by the marketplace team.

Due to this I am closing this as out of scope.
Hope this makes sense.
