### ISSUE TITLE
error

### ISSUE THREAD

**Issue by electraaaaaaa** [microsoft/vscode-docs#6453]
![Screenshot_2](https://github.com/microsoft/vscode-docs/assets/101008009/fe2c9c0e-8c4d-43f5-8126-7ff025b721f7)
![Screenshot_3](https://github.com/microsoft/vscode-docs/assets/101008009/13f7dc9e-ae00-40d6-9f68-b876c2494d70)
![Screenshot_4](https://github.com/microsoft/vscode-docs/assets/101008009/95e5fe3d-acfa-4ece-9edd-b6ac22f98f0d)

i cant fix this

**Comment by gregvanl** [comment]
Hi @electraaaaaaa Have you restarted VS Code since you installed your C++ compilers so that it inherits the PATH environment?
You could also try a Command Prompt terminal in VS Code and see it your issue is limited to PowerShell.

![image](https://github.com/microsoft/vscode-docs/assets/12818376/45e53922-4019-41da-bb75-a74d99fb3530)
