### ISSUE TITLE
Multi-root workspace support documentation for language extensions

### ISSUE THREAD

**Issue by Seboran** [microsoft/vscode-docs#6458]
Hello

The file overview.md file for language-extensions for multi-root workspace support.

See https://github.com/Microsoft/vscode-docs/blob/main/api/language-extensions/overview.md#multi-root-workspace-support

Could ie be possible to remove this part, as it doesn't tell what to do and doesn't tell which topic ?

> Multi-root workspace support
When the user opens a [multi-root workspace](https://github.com/microsoft/vscode-docs/blob/main/docs/editor/multi-root-workspaces), you might need to adapt your Language Server extensions accordingly. This topic discusses multiple approaches to supporting multi-root workspaces.

**Comment by gregvanl** [comment]
Hi @Seboran, the linked to topic https://code.visualstudio.com/docs/editor/multi-root-workspaces has a section for extension authors at https://code.visualstudio.com/docs/editor/multi-root-workspaces#_extensions, which contains a link to a wiki page with details https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs

Rather than remove that section in the overview, would it be helpful to link directly to the "Extensions" section of the "Multi-root Workspaces" topic?

**Comment by gregvanl** [comment]
Closing older issue with no response
