### ISSUE TITLE
Rendering error when @example not followed by <caption>

### ISSUE THREAD

**Issue by md2perpe** [microsoft/vscode-docs#6490]
I noticed this rendering issue in the example for [DocumentSelector](https://code.visualstudio.com/api/references/vscode-api#DocumentSelector):
<img width="654" alt="Skärmavbild 2023-07-14 kl  11 32 15" src="https://github.com/microsoft/vscode/assets/543239/b5fa9b33-1d9a-42af-aa58-b03e71b30509">

It obviously comes from [vscode.d.ts lines 2191-2192](https://github.com/microsoft/vscode/blob/6a152ca5231c2035bc8718e41dc96047e33bed96/src/vscode-dts/vscode.d.ts#L2191-L2192) but I'm not sure what is needed to fix it.

Is it enough adding a space after `@example` or is a `<caption>` element needed?

There are other cases with the same rendering issue.

**Comment by gregvanl** [comment]
This is fixed in the API generation code and will be published shortly.

![image](https://github.com/microsoft/vscode-docs/assets/12818376/5f310a81-a241-47bf-80b5-c411dee6d19c)

**Comment by md2perpe** [comment]
Do you have a link to the PR or commit where it's fixed?

**Comment by gregvanl** [comment]
Hi @md2perpe The API reference generation code, where the fix was made, is in the vscode-website infrastructure repo, which is private. 
I can tell you that the fix involved updating the version of the typedoc (https://typedoc.org) that we use to render the vscode.d.ts file (https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.d.ts)
