### ISSUE TITLE
visual studio code

### ISSUE THREAD

**Issue by saurabhnachankar** [Microsoft/vscode-docs#671]
Commented code shows up error while debugging..

Visual Studio code is inappropriate for developers to keep coding up

**Comment by gregvanl** [comment]
Hi @saurabhnachankar,
This repo is for the VS Code online documentation. It looks like your issue is related to the VS Code editor itself. You can enter issues for the product at https://github.com/Microsoft/vscode/issues.
If you do enter an issue, please add more details such as the debugger used (Node.js, C#, PHP?) and an example of the commented code showing an error.
Thanks

**Comment by saurabhnachankar** [comment]
This was my controller's method invoking for creating XL file through
Epplus.

*Issue No. 1  :* This was my following using :  using
Microsoft.Net.Http.Headers; for ContentDispositionHeaderValue.
But i was not able to get it through intelligence in Visual Studio Code. so
i opened it in visual studio community and got the appropriate using.

*Eg :*
Response.Headers["Content-Disposition"] = new
ContentDispositionHeaderValue("attachment")

*Issue No 2 :* Even commented code is complied in debugger (C#) and later
shows the following error of commented code like

*Eg :*


*In Browser error:*
An error occurred during the compilation of a resource required to process
this request. Please review the following specific error details and modify
your source code appropriately.
Please fix the issue of VS-Code

Regards,
Saurabh Nachankar
