### ISSUE TITLE
Update overall getting started experience

### ISSUE THREAD

**Issue by ntrogh** [microsoft/vscode-docs#7359]
Improve the overall getting started docs experience for new users.

- [x] Review getting started documentation section and 
- [x] Create an outline for a guided getting started experience.
- [ ] Create Getting Started tutorial
- [ ] Update docs landing page and CTAs
- [ ] Evaluate how we can align the in-product walkthroughs with the Getting Started tutorial.

**Comment by ntrogh** [comment]
Outline for Getting Started Tutorial:

* Start VS Code
    * Use the OS GUI or start from the command line
    * Welcome page & walkthroughs
* Open a workspace
    * Create a new folder
    * Open folder in VS Code
    * Explain concept of workspace
* Learn about the user interface
    * Activity Bar + views
    * Editor
    * Panel (mention integrated terminal)
    * Command Palette
* Extensions
    * Language extensions (intellisense, debugging, testing, ...)
    * Other (themes, ...)
* Customize VS Code
    * Appearance (themes)
    * Settings
    * Keybindings
* Next steps
    * Tips & tricks
    * Source control
    * Integrated terminal
    * Debugging
    * Testing

@bhavyaus here's a first draft of the outline for the VS Code getting started tutorial. Do you see any key topics that are missing for someone's first experience with VS Code?

**Comment by ntrogh** [comment]
@bamurtaugh sharing the draft outline for a VS Code Getting Started tutorial. Any feedback is welcome!

**Comment by bhavyaus** [comment]
1. Should `Customize VS Code` section appear right after the `Learn about the user interface` section? Past user studies suggest that offering some level of customization at the start of user interactions tends to result in sustained engagement -> the first step in the getting started walkthrough is **"Choose your theme".**
@daviddossett might have more info here. 

2. `Install a language extension` should be before `Edit a code file` so that users can edit and run the code in the language of their choice.

**Comment by ntrogh** [comment]
@bhavyaus thanks for the feedback. I'll incorporate it.

**Comment by bamurtaugh** [comment]
Thanks for putting this together, looks great!

I think it could be interesting incorporate Remote Development and GitHub Copilot, maybe as Next Steps? They could become fundamental to how users develop with VS Code everyday, so I think they could make sense to highlight somewhere in a getting started.
