### ISSUE TITLE
Bug - The Search Docs input box in the landing page does not work 

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode-docs#7579]
Hi,

The `Search Docs` input box located at the top bar of the VS Code home page (https://code.visualstudio.com) is not working properly. No matter the term you search for, it always return _No results_.

On the other hand, if you use the input box in the `Search` page (https://code.visualstudio.com/Search), the search works just fine.

Thank you

**Comment by ntrogh** [comment]
@rzhao271 Can you investigate why the search is down?

**Comment by DanTup** [comment]
> On the other hand, if you use the input box in the Search page (https://code.visualstudio.com/Search), the search works just fine.

That doesn't work for me, it's broken from both places:

https://github.com/user-attachments/assets/b7e12334-0193-4cb2-913a-569968b09d38

**Comment by rzhao271** [comment]
Confirmed that search is down and that searching `settings site:code.visualstudio.com` on Bing does not work.

**Comment by gjsjohnmurray** [comment]
Any update on this?

**Comment by rzhao271** [comment]
I found that search results from [code.visualstudio.com](http://code.visualstudio.com/) show up in Google and DuckDuckGo, so this issue seems to be specific to Bing.

Because the in-site search UX relies on Bing, it is still broken. No ETA on a fix at this time.
I used Bing Webmaster Tools yesterday and today and have not encountered any detailed error messages.

**Comment by rzhao271** [comment]
Bing Webmaster Tools is able to index the site, now.
In-site search works for me again!

**Comment by gjsjohnmurray** [comment]
Confirmed OK for me too,

**Comment by alefragnani** [comment]
Confirmed it is working perfectly for me too. 

Thank you!
